#!/usr/bin/env bash
# tests/test_export_repro_audit_build_script.sh — pin the
# .audit/build.sh splice path in bin/export-repro.
#
# When the audit converged on a build recipe via bin/auto-build-script,
# the recipe lives at TARGET_ROOT/.audit/build.sh. export-repro must
# inline that recipe verbatim into reproduce.sh in place of the
# hardcoded cmake template, so the reproducer build matches the
# audit's build by construction. This test fails if the splice is
# removed or the fallback template comes back.

set -o pipefail
source "$(dirname "$0")/helpers.sh"
setup_test_env

trap 'teardown_test_env' EXIT

OUT="$TEST_TMPDIR/output/abs-test"
RESULTS="$OUT/results"
CRASH="$RESULTS/crashes/CRASH-ABS-1"
SRC="$TEST_TMPDIR/fake-src"
mkdir -p "$OUT" "$CRASH" "$SRC/.git" "$SRC/.audit"

cat > "$OUT/target.toml" <<EOF
slug = "abs-test"
upstream_url = "https://example.com/fake"
build_system = "cmake"
pinned_rev = "deadbeef"
asan_bin = "build-asan/unused"
asan_lib = ""
includes = []
link_libs = []
is_browser = "0"

[threat_model]
attacker_controls = ["bytes"]
EOF
cat > "$OUT/.session-env" <<EOF
RESULTS_DIR=$RESULTS
TARGET_ROOT=$SRC
TARGET_SLUG=abs-test
TARGET_REV=deadbeef
LOGDIR=$TEST_TMPDIR/logs
EOF

# Sentinel-bearing .audit/build.sh — if the splice happens, the
# generated reproduce.sh must contain this exact byte sequence.
SENTINEL="SENTINEL_ABS_$(date +%s)_$$"
cat > "$SRC/.audit/build.sh" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by bin/auto-build-script.
set -eu
src="\$1"; build="\$2"
mkdir -p "\$build"
echo "$SENTINEL" > "\$build/.sentinel"
EOF
chmod +x "$SRC/.audit/build.sh"

# Minimal crash dir
cat > "$CRASH/harness.c" <<'EOF'
#include <stdio.h>
int main(int argc, char **argv) { (void)argc; (void)argv; return 0; }
EOF
printf 'AAAA' > "$CRASH/input.bin"
cat > "$CRASH/asan.txt" <<'EOF'
ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x
=== Run 1/1 ===
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead at pc 0xface
READ of size 1 at 0xdead thread T0
    #0 0xdead in main /src/harness.c:2
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/harness.c:2 in main
CRASH_RATE: 1/1
EOF
cat > "$CRASH/report.md" <<'EOF'
# CRASH-ABS-1
## Summary
Fixture.
Trigger source: bytes
Caller contract: obeyed
Boundary: input file
Caller controls: bytes
EOF

( cd "$OUT" && "$SCRIPT_ROOT/bin/export-repro" CRASH-ABS-1 ) > "$TEST_TMPDIR/out" 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
  pass "export-repro splice path exits 0"
else
  fail "export-repro splice path exits 0" "rc=$rc out=$(tail -c 600 "$TEST_TMPDIR/out")"
  summary
  exit 1
fi

assert_file_exists "$CRASH/reproduce.sh" "splice: reproduce.sh emitted"
assert_file_contains "$CRASH/reproduce.sh" "$SENTINEL" \
  "splice: .audit/build.sh contents inlined into reproduce.sh"
assert_file_contains "$CRASH/reproduce.sh" '\.audit-build\.sh' \
  "splice: reproduce.sh invokes the materialized audit-build script"
assert_file_not_contains "$CRASH/reproduce.sh" 'DCMAKE_BUILD_TYPE=RelWithDebInfo' \
  "splice: legacy hardcoded cmake template NOT also emitted"
assert_file_contains "$CRASH/reproduce.sh" 'AUDIT_BUILD_SCRIPT_EOF' \
  "splice: heredoc delimiter present"

# ─── Lib resolver fallback (canonical-form match) ──────────────────────
# Build a fake build tree under TEST_TMPDIR and exercise the
# stem-stripping fallback. The reproduce.sh's LIB_RESOLVE block is shell;
# extract the block, point san_lib at a non-existent operator-local
# decorated name, and confirm the fallback finds the canonical form.
build="$TEST_TMPDIR/fake-build"
mkdir -p "$build/lib"
: > "$build/lib/libfoo.a"   # canonical archive
# Extract the LIB_RESOLVE chunk into a standalone script for testing.
awk '/^san_lib=/,/^\[ -f "\$san_lib" \] \|\| { echo/{print}' "$CRASH/reproduce.sh" \
  > "$TEST_TMPDIR/resolve.sh" 2>/dev/null
# Headless test: there's no san_lib emitted in this fixture (asan_lib was
# empty in target.toml), so resolve.sh is empty. The lib-resolver pin is
# better covered by an end-to-end run against real cjson/curl, which is
# what we did manually before committing. Just assert the template still
# carries the canonical-form fallback string so a refactor that drops the
# whole block fails this test.
assert_file_contains "$SCRIPT_ROOT/bin/export-repro" 'Strip audit-side decoration' \
  "lib-resolver: stem-decoration strip is documented in LIB_RESOLVE template"
assert_file_contains "$SCRIPT_ROOT/bin/export-repro" '\*-asan|\*-ubsan|\*-msan|\*-tsan|\*-d|\*-debug' \
  "lib-resolver: stem-suffix strip list present in LIB_RESOLVE template"

# ─── Fallback WARN when .audit/build.sh is missing ───────────────────
# This is the bug that silently shipped pre-fix: the splice path didn't
# trigger, export-repro fell back to the generic cmake template, the
# operator had no idea, and the bundle landed in maintainers' inboxes
# with a build that didn't reflect the audit. WARN makes the fallback
# loud so the operator sees the missing build.sh.
rm -f "$SRC/.audit/build.sh"
CRASH2="$RESULTS/crashes/CRASH-ABS-2"
mkdir -p "$CRASH2"
cat > "$CRASH2/harness.c" <<'EOF'
#include <stdio.h>
int main(int argc, char **argv) { (void)argc; (void)argv; return 0; }
EOF
printf 'AAAA' > "$CRASH2/input.bin"
cat > "$CRASH2/asan.txt" <<'EOF'
ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x
=== Run 1/1 ===
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead at pc 0xface
READ of size 1 at 0xdead thread T0
    #0 0xdead in main /src/harness.c:2
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/harness.c:2 in main
CRASH_RATE: 1/1
EOF
cat > "$CRASH2/report.md" <<'EOF'
# CRASH-ABS-2
## Summary
Fixture.
Trigger source: bytes
Caller contract: obeyed
Boundary: input file
Caller controls: bytes
EOF
( cd "$OUT" && "$SCRIPT_ROOT/bin/export-repro" CRASH-ABS-2 ) > "$TEST_TMPDIR/out2" 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
  pass "export-repro fallback path exits 0"
else
  fail "export-repro fallback path exits 0" "rc=$rc out=$(tail -c 600 "$TEST_TMPDIR/out2")"
fi
assert_file_contains "$TEST_TMPDIR/out2" 'WARN.*\.audit/build\.sh.*missing' \
  "fallback: WARN names the missing build.sh file"
assert_file_contains "$TEST_TMPDIR/out2" 'setup-target.*--build' \
  "fallback: WARN points operator at setup-target --build"

# ─── CLI-with-input path also inlines the recipe ──────────────────────
# Regression for the bug where only the C-harness template threaded
# audit_build_script: a CLI target (tool -i input, no harness — the
# ffmpeg/curl shape) silently fell back to the generic autotools bucket
# template and rebuilt the wrong binary. With the fix, every build-
# emitting template inlines .audit/build.sh, and the dispatch-level guard
# hard-fails if one ever stops.
OUT_CLI="$TEST_TMPDIR/output/cli-test"
RESULTS_CLI="$OUT_CLI/results"
CRASH_CLI="$RESULTS_CLI/crashes/CRASH-CLI-1"
SRC_CLI="$TEST_TMPDIR/fake-src-cli"
mkdir -p "$OUT_CLI" "$CRASH_CLI" "$SRC_CLI/.git" "$SRC_CLI/.audit"
cat > "$OUT_CLI/target.toml" <<EOF
slug = "cli-test"
upstream_url = "https://example.com/fake"
build_system = "autotools"
pinned_rev = "deadbeef"
asan_bin = "build-asan/tool"
asan_lib = ""
includes = []
link_libs = []
is_browser = "0"

[threat_model]
attacker_controls = ["bytes"]
EOF
cat > "$OUT_CLI/.session-env" <<EOF
RESULTS_DIR=$RESULTS_CLI
TARGET_ROOT=$SRC_CLI
TARGET_SLUG=cli-test
TARGET_REV=deadbeef
LOGDIR=$TEST_TMPDIR/logs
EOF
SENTINEL_CLI="SENTINEL_CLI_$(date +%s)_$$"
cat > "$SRC_CLI/.audit/build.sh" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by bin/auto-build-script.
set -eu
src="\$1"; build="\$2"
mkdir -p "\$build"
echo "$SENTINEL_CLI" > "\$build/.sentinel"
EOF
chmod +x "$SRC_CLI/.audit/build.sh"
# No harness.c — a bare CLI testcase routes through the input_name branch.
printf 'AAAA' > "$CRASH_CLI/input.bin"
cat > "$CRASH_CLI/asan.txt" <<'EOF'
ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x
=== Run 1/1 ===
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead at pc 0xface
READ of size 1 at 0xdead thread T0
    #0 0xdead in app_parse /src/app.c:2
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/app.c:2 in app_parse
CRASH_RATE: 1/1
EOF
cat > "$CRASH_CLI/report.md" <<'EOF'
# CRASH-CLI-1
## Summary
Fixture.
Trigger source: bytes
Caller contract: obeyed
Boundary: input file
Caller controls: bytes
EOF
( cd "$OUT_CLI" && "$SCRIPT_ROOT/bin/export-repro" CRASH-CLI-1 ) > "$TEST_TMPDIR/out_cli" 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
  pass "export-repro CLI-with-input path exits 0"
else
  fail "export-repro CLI-with-input path exits 0" "rc=$rc out=$(tail -c 600 "$TEST_TMPDIR/out_cli")"
fi
assert_file_contains "$CRASH_CLI/reproduce.sh" "$SENTINEL_CLI" \
  "cli: .audit/build.sh contents inlined into CLI reproduce.sh"
assert_file_contains "$CRASH_CLI/reproduce.sh" '\.audit-build\.sh' \
  "cli: CLI reproduce.sh invokes the materialized audit-build script"
assert_file_not_contains "$CRASH_CLI/reproduce.sh" 'configure --disable-shared --enable-static' \
  "cli: generic autotools bucket template NOT emitted when a recipe exists"

# reproduce.sh must canonicalize $src to an absolute path before building.
# Out-of-tree autotools (and the inlined recipe) `cd "$build"` then run
# "$src/configure"; a relative src (./<slug> from `./reproduce.sh`) resolves
# against the build dir and the configure script vanishes.
assert_file_contains "$CRASH_CLI/reproduce.sh" 'src="\$\(cd "\$src" && pwd\)"' \
  "cli: reproduce.sh resolves \$src to an absolute path before the build"

# Pin the dispatch-level guard so a future writer that drops the recipe
# (the regression that started all this) fails loudly instead of shipping
# a guessed build.
assert_file_contains "$SCRIPT_ROOT/bin/export-repro" 'did not inline it' \
  "guard: dispatch hard-fails when a loaded recipe is not inlined"

summary
