#!/usr/bin/env bash
# tests/test_export_repro_audit_build_script.sh — pin the
# .audit/build.sh splice path in bin/export-repro.
#
# When the audit converged on a build recipe via bin/auto-build-script,
# the recipe lives at TARGET_ROOT/.audit/build.sh. export-repro must
# inline that recipe verbatim into reproduce.sh in place of the
# hardcoded cmake template, so the reproducer build matches the
# audit's build by construction. This test fails if the splice is
# removed or the fallback template comes back.

set -o pipefail
source "$(dirname "$0")/helpers.sh"
setup_test_env

trap 'teardown_test_env' EXIT

OUT="$TEST_TMPDIR/output/abs-test"
RESULTS="$OUT/results"
CRASH="$RESULTS/crashes/CRASH-ABS-1"
SRC="$TEST_TMPDIR/fake-src"
mkdir -p "$OUT" "$CRASH" "$SRC/.git" "$SRC/.audit"

cat > "$OUT/target.toml" <<EOF
slug = "abs-test"
upstream_url = "https://example.com/fake"
build_system = "cmake"
pinned_rev = "deadbeef"
asan_bin = "build-asan/unused"
asan_lib = ""
includes = []
link_libs = []
is_browser = "0"

[threat_model]
attacker_controls = ["bytes"]
EOF
cat > "$OUT/.session-env" <<EOF
RESULTS_DIR=$RESULTS
TARGET_ROOT=$SRC
TARGET_SLUG=abs-test
TARGET_REV=deadbeef
LOGDIR=$TEST_TMPDIR/logs
EOF

# Sentinel-bearing .audit/build.sh — if the splice happens, the
# generated reproduce.sh must contain this exact byte sequence.
SENTINEL="SENTINEL_ABS_$(date +%s)_$$"
cat > "$SRC/.audit/build.sh" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by bin/auto-build-script.
set -eu
src="\$1"; build="\$2"
mkdir -p "\$build"
echo "$SENTINEL" > "\$build/.sentinel"
EOF
chmod +x "$SRC/.audit/build.sh"

# Minimal crash dir
cat > "$CRASH/harness.c" <<'EOF'
#include <stdio.h>
int main(int argc, char **argv) { (void)argc; (void)argv; return 0; }
EOF
printf 'AAAA' > "$CRASH/input.bin"
cat > "$CRASH/asan.txt" <<'EOF'
ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x
=== Run 1/1 ===
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead at pc 0xface
READ of size 1 at 0xdead thread T0
    #0 0xdead in main /src/harness.c:2
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/harness.c:2 in main
CRASH_RATE: 1/1
EOF
cat > "$CRASH/report.md" <<'EOF'
# CRASH-ABS-1
## Summary
Fixture.
Trigger source: bytes
Caller contract: obeyed
Boundary: input file
Caller controls: bytes
EOF

( cd "$OUT" && "$SCRIPT_ROOT/bin/export-repro" CRASH-ABS-1 ) > "$TEST_TMPDIR/out" 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
  pass "export-repro splice path exits 0"
else
  fail "export-repro splice path exits 0" "rc=$rc out=$(tail -c 600 "$TEST_TMPDIR/out")"
  summary
  exit 1
fi

assert_file_exists "$CRASH/reproduce.sh" "splice: reproduce.sh emitted"
assert_file_contains "$CRASH/reproduce.sh" "$SENTINEL" \
  "splice: .audit/build.sh contents inlined into reproduce.sh"
assert_file_contains "$CRASH/reproduce.sh" '\.audit-build\.sh' \
  "splice: reproduce.sh invokes the materialized audit-build script"
assert_file_not_contains "$CRASH/reproduce.sh" 'DCMAKE_BUILD_TYPE=RelWithDebInfo' \
  "splice: legacy hardcoded cmake template NOT also emitted"
assert_file_contains "$CRASH/reproduce.sh" 'AUDIT_BUILD_SCRIPT_EOF' \
  "splice: heredoc delimiter present"

# ─── Lib resolver fallback (canonical-form match) ──────────────────────
# Build a fake build tree under TEST_TMPDIR and exercise the
# stem-stripping fallback. The reproduce.sh's LIB_RESOLVE block is shell;
# extract the block, point san_lib at a non-existent operator-local
# decorated name, and confirm the fallback finds the canonical form.
build="$TEST_TMPDIR/fake-build"
mkdir -p "$build/lib"
: > "$build/lib/libfoo.a"   # canonical archive
# Extract the LIB_RESOLVE chunk into a standalone script for testing.
awk '/^san_lib=/,/^\[ -f "\$san_lib" \] \|\| { echo/{print}' "$CRASH/reproduce.sh" \
  > "$TEST_TMPDIR/resolve.sh" 2>/dev/null
# Headless test: there's no san_lib emitted in this fixture (asan_lib was
# empty in target.toml), so resolve.sh is empty. The lib-resolver pin is
# better covered by an end-to-end run against real cjson/curl, which is
# what we did manually before committing. Just assert the template still
# carries the canonical-form fallback string so a refactor that drops the
# whole block fails this test.
assert_file_contains "$SCRIPT_ROOT/bin/export-repro" 'Strip audit-side decoration' \
  "lib-resolver: stem-decoration strip is documented in LIB_RESOLVE template"
assert_file_contains "$SCRIPT_ROOT/bin/export-repro" '\*-asan|\*-ubsan|\*-msan|\*-tsan|\*-d|\*-debug' \
  "lib-resolver: stem-suffix strip list present in LIB_RESOLVE template"

# ─── Fallback WARN when .audit/build.sh is missing ───────────────────
# This is the bug that silently shipped pre-fix: the splice path didn't
# trigger, export-repro fell back to the generic cmake template, the
# operator had no idea, and the bundle landed in maintainers' inboxes
# with a build that didn't reflect the audit. WARN makes the fallback
# loud so the operator sees the missing build.sh.
rm -f "$SRC/.audit/build.sh"
CRASH2="$RESULTS/crashes/CRASH-ABS-2"
mkdir -p "$CRASH2"
cat > "$CRASH2/harness.c" <<'EOF'
#include <stdio.h>
int main(int argc, char **argv) { (void)argc; (void)argv; return 0; }
EOF
printf 'AAAA' > "$CRASH2/input.bin"
cat > "$CRASH2/asan.txt" <<'EOF'
ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x
=== Run 1/1 ===
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead at pc 0xface
READ of size 1 at 0xdead thread T0
    #0 0xdead in main /src/harness.c:2
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/harness.c:2 in main
CRASH_RATE: 1/1
EOF
cat > "$CRASH2/report.md" <<'EOF'
# CRASH-ABS-2
## Summary
Fixture.
Trigger source: bytes
Caller contract: obeyed
Boundary: input file
Caller controls: bytes
EOF
( cd "$OUT" && "$SCRIPT_ROOT/bin/export-repro" CRASH-ABS-2 ) > "$TEST_TMPDIR/out2" 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
  pass "export-repro fallback path exits 0"
else
  fail "export-repro fallback path exits 0" "rc=$rc out=$(tail -c 600 "$TEST_TMPDIR/out2")"
fi
assert_file_contains "$TEST_TMPDIR/out2" 'WARN.*\.audit/build\.sh.*missing' \
  "fallback: WARN names the missing build.sh file"
assert_file_contains "$TEST_TMPDIR/out2" 'setup-target.*--build' \
  "fallback: WARN points operator at setup-target --build"

summary
