#!/usr/bin/env python3
"""A reproducer driver tests the pinned build, never a build of its own."""

from __future__ import annotations

import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "lib"))

import build_scope  # noqa: E402
import sanitizer  # noqa: E402
import triage  # noqa: E402
import workqueue  # noqa: E402

DIAGNOSTIC = """\
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x1
READ of size 1 at 0x1 thread T0
    #0 0x1 in app_parse sample.c:12
SUMMARY: AddressSanitizer: heap-buffer-overflow sample.c:12 in app_parse
"""

REPORT = """\
# CRASH-001-1

## Summary

app_parse reads past its buffer.

## Fields

Boundary: public parse API
Caller controls: bytes
Trusted caller actions: none
Caller contract: obeyed
Trigger source: bytes
Strategy: S7
"""


def _clang_available() -> bool:
    return shutil.which(sanitizer.llvm_tool("clang")) is not None


class CompiledTargetUnitsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="build-scope-")
        self.root = Path(self.temporary.name)
        self.target = self.root / "targets" / "sampleproj"
        (self.target / "src").mkdir(parents=True)
        (self.target / "sample.h").write_text("int app_parse(const char *);\n")
        (self.target / "sample.c").write_text(
            '#include "sample.h"\nint app_parse(const char *s) { return s[0]; }\n',
        )
        (self.target / "src" / "extra.c").write_text("int extra(void) { return 1; }\n")
        self.crash = self.root / "results" / "crashes" / "CRASH-001-1"
        self.crash.mkdir(parents=True)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def driver(self, body: str, name: str = "harness.c") -> Path:
        path = self.crash / name
        path.write_text(body, encoding="utf-8")
        return path

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_driver_linking_the_pinned_build_compiles_no_target_unit(self) -> None:
        driver = self.driver(
            '#include "sample.h"\n#include "missing_generated.h"\n'
            "int main(void) { return app_parse(\"x\"); }\n",
        )
        # A header the scan cannot find (generated by the build) neither
        # fails the scan nor counts as a compiled unit.
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [])

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_driver_including_target_sources_names_each_unit_once(self) -> None:
        driver = self.driver(
            '#include "sample.c"\n#include "src/extra.c"\n#include "sample.c"\n'
            "int main(void) { return app_parse(\"x\") + extra(); }\n",
        )
        self.assertEqual(
            build_scope.compiled_target_units(driver, self.target),
            [Path("sample.c"), Path("src/extra.c")],
        )

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_source_outside_the_target_tree_is_not_a_target_unit(self) -> None:
        (self.crash / "helper.c").write_text("int helper(void) { return 0; }\n")
        driver = self.driver('#include "helper.c"\nint main(void) { return helper(); }\n')
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [])

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_unit_named_through_a_configured_include_dir_is_placed(self) -> None:
        # The model's own compile line used `-I src`, so the driver names the
        # unit bare; without that directory the scan sees only a token.
        driver = self.driver('#include "extra.c"\nint main(void) { return extra(); }\n')
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [])
        (driver.parent / build_scope.CACHE_NAME).unlink()
        self.assertEqual(
            build_scope.compiled_target_units(
                driver, self.target, include_dirs=(self.target / "src",),
            ),
            [Path("src/extra.c")],
        )

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_build_generated_config_gates_the_include_the_scan_follows(self) -> None:
        build = self.target / "build-asan"
        build.mkdir()
        (build / "config.h").write_text("#define USE_EXTRA 1\n")
        driver = self.driver(
            '#include "config.h"\n#ifdef USE_EXTRA\n#include "src/extra.c"\n#endif\n'
            "int main(void) { return 0; }\n",
        )
        # Without the build directory the macro never defines and the unit is
        # never opened: a documented limit of the scan, not a verdict.
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [])
        (driver.parent / build_scope.CACHE_NAME).unlink()
        self.assertEqual(
            build_scope.compiled_target_units(driver, self.target, include_dirs=(build,)),
            [Path("src/extra.c")],
        )

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_cxx_driver_and_cached_answer(self) -> None:
        driver = self.driver(
            '#include <string>\nextern "C" {\n#include "sample.c"\n}\n'
            "int main() { std::string s; return app_parse(s.c_str()); }\n",
            name="harness.cc",
        )
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [Path("sample.c")])
        cache = driver.parent / build_scope.CACHE_NAME
        self.assertTrue(cache.is_file())
        with mock.patch.object(build_scope.timeout, "run_timeout") as scan:
            self.assertEqual(
                build_scope.compiled_target_units(driver, self.target), [Path("sample.c")],
            )
            scan.assert_not_called()
        driver.write_text("int main() { return 0; }\n")
        self.assertEqual(build_scope.compiled_target_units(driver, self.target), [])

    def test_configured_include_dirs_come_from_the_session_snapshot(self) -> None:
        results = self.crash.parent.parent
        (results / ".target.toml").write_text(
            'includes = [".", "build-asan/include"]\n', encoding="utf-8",
        )
        self.assertEqual(
            triage._configured_include_dirs(results, self.target),
            (self.target, self.target / "build-asan" / "include"),
        )
        (results / ".target.toml").unlink()
        self.assertEqual(triage._configured_include_dirs(results, self.target), ())

    def test_missing_target_root_is_a_failed_scan_not_a_verdict(self) -> None:
        driver = self.driver("int main(void) { return 0; }\n")
        self.assertIsNone(
            build_scope.compiled_target_units(driver, self.root / "absent"),
        )

    @unittest.skipUnless(_clang_available(), "no clang for the dependency scan")
    def test_crash_triage_demotes_a_driver_that_compiles_target_source(self) -> None:
        results = self.crash.parent.parent
        (self.crash / "sanitizer.txt").write_text(DIAGNOSTIC, encoding="utf-8")
        (self.crash / "report.md").write_text(REPORT, encoding="utf-8")
        (self.crash / "input.bin").write_bytes(b"x")
        self.driver(
            '#include "sample.c"\n'
            "int main(int argc, char **argv) { return app_parse(argv[1]); }\n",
        )
        status = triage.triage_one_crash(
            self.crash, results, self.target, "sampleproj", ["bytes"],
            deadline=None, age_pending=False,
        )
        self.assertEqual(status, "demoted")
        self.assertFalse(self.crash.exists())
        demoted = results / "findings" / "FIND-001-1"
        self.assertTrue(demoted.is_dir())
        disposition = (demoted / "report.md").read_text(encoding="utf-8")
        self.assertIn("Demoted from `crashes/`", disposition)
        self.assertIn("sample.c", disposition)
        self.assertIn("pinned build", disposition)


class ReconcileArtifactHypothesesTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="reconcile-")
        self.results = Path(self.temporary.name) / "results"
        self.state = self.results / "state"
        self.state.mkdir(parents=True)
        self.rows = [
            {"id": "H-aaaaaaaaaa", "agent": "2", "status": "PENDING", "card_id": "WORK-1", "note": "guard at line 12"},
            {"id": "H-bbbbbbbbbb", "agent": "2", "status": "DISCARDED", "card_id": "WORK-1"},
            {"id": "H-cccccccccc", "agent": "1", "status": "INVESTIGATING", "card_id": "WORK-2"},
        ]
        workqueue.write_jsonl(self.state / "hypotheses.jsonl", self.rows)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def read(self) -> dict[str, dict]:
        return {
            row["id"]: row
            for row in workqueue.read_jsonl(self.state / "hypotheses.jsonl")
        }

    def test_accepted_finding_closes_the_hypothesis_its_testcase_names(self) -> None:
        finding = self.results / "findings" / "FIND-010-compare"
        finding.mkdir(parents=True)
        (finding / "report.md").write_text("see H-cccccccccc for context\n")
        (finding / "testcase.txt").write_text(
            "# TARGET: sample.c:app_parse\n# HYPOTHESIS-ID: H-aaaaaaaaaa\n# CATEGORY: state\n{}",
        )
        changed = workqueue.reconcile_artifact_hypotheses(self.results, finding)
        self.assertEqual(changed, ["H-aaaaaaaaaa"])
        rows = self.read()
        self.assertEqual(rows["H-aaaaaaaaaa"]["status"], "FIND-010-compare")
        self.assertEqual(
            rows["H-aaaaaaaaaa"]["note"],
            "guard at line 12; closed by triage: FIND-010-compare accepted with "
            "this hypothesis in its evidence header",
        )
        # A report's prose is discussion, not provenance: the row it mentions
        # stays open, and a terminal row keeps its own verdict.
        self.assertEqual(rows["H-cccccccccc"]["status"], "INVESTIGATING")
        self.assertEqual(rows["H-bbbbbbbbbb"]["status"], "DISCARDED")

    def test_terminal_row_and_header_less_bundle_are_left_alone(self) -> None:
        crash = self.results / "crashes" / "CRASH-003-2"
        (crash / ".audit").mkdir(parents=True)
        (crash / "input.bin").write_bytes(b"\x00\x01")
        (crash / ".audit" / "testcase.c").write_text(
            "// TARGET: sample.c\n// HYPOTHESIS-ID: H-bbbbbbbbbb\n// CATEGORY: bounds\n",
        )
        before = (self.state / "hypotheses.jsonl").stat().st_mtime_ns
        self.assertEqual(workqueue.reconcile_artifact_hypotheses(self.results, crash), [])
        self.assertEqual(self.read()["H-bbbbbbbbbb"]["status"], "DISCARDED")
        # Nothing to close means nothing rewritten under the lock.
        self.assertEqual((self.state / "hypotheses.jsonl").stat().st_mtime_ns, before)
        self.assertEqual(
            workqueue.reconcile_artifact_hypotheses(self.results, self.results / "findings" / "FIND-404"),
            [],
        )

    def test_accepted_artifact_join_reads_the_reconciled_status(self) -> None:
        finding = self.results / "findings" / "FIND-011"
        finding.mkdir(parents=True)
        (finding / "testcase.txt").write_text("# HYPOTHESIS-ID: H-aaaaaaaaaa\n# TARGET: x\n")
        triage._record_accepted_artifact(finding, self.results, "find")
        claims = workqueue.read_jsonl(self.state / "claims.jsonl")
        self.assertEqual(
            [(row["card_id"], row["artifact"], row["source"]) for row in claims],
            [("WORK-1", "FIND-011", "accepted-artifact")],
        )


if __name__ == "__main__":
    unittest.main()
