#!/usr/bin/env python3
"""Generated reproducer integration with the converged audit build recipe."""

from __future__ import annotations

import hashlib
import json
import subprocess
import tempfile
import unittest
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
EXPORT = ROOT / "bin" / "export-repro"


class ExportReproducerAuditBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="export-repro-build-")
        self.root = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def make_layout(self, slug, build_system="cmake", asan_bin="build-asan/unused"):
        output = self.root / "output" / slug
        results = output / "codex" / "results"
        source = self.root / ("source-" + slug)
        (source / ".git").mkdir(parents=True)
        (source / ".audit").mkdir()
        output.mkdir(parents=True)
        (output / "target.toml").write_text(
            f'slug = "{slug}"\nupstream_url = "https://example.com/fake"\n'
            f'build_system = "{build_system}"\npinned_rev = "deadbeef"\n'
            f'asan_bin = "{asan_bin}"\nasan_lib = ""\nincludes = []\nlink_libs = []\n'
            'is_browser = "0"\n\n[threat_model]\nattacker_controls = ["bytes"]\n'
        )
        (results / ".session-env").parent.mkdir(parents=True)
        (results / ".session-env").write_text(
            f"RESULTS_DIR={results}\nTARGET_ROOT={source}\nTARGET_SLUG={slug}\n"
            f"TARGET_REV=deadbeef\nLOGDIR={self.root / 'logs'}\n"
        )
        return output, results, source

    def write_recipe(self, source, sentinel):
        recipe = source / ".audit" / "build.sh"
        recipe.write_text(
            "#!/usr/bin/env bash\n# AUTO-GENERATED by bin/auto-build-script.\nset -eu\n"
            'src="$1"; build="$2"\nmkdir -p "$build"\n'
            f'echo "{sentinel}" > "$build/.sentinel"\n'
        )
        recipe.chmod(0o755)

    def write_crash(self, results, crash_id, harness=True):
        crash = results / "crashes" / crash_id
        crash.mkdir(parents=True)
        if harness:
            (crash / "harness.c").write_text(
                "#include <stdio.h>\nint main(int argc, char **argv) { return argc && argv ? 0 : 1; }\n"
            )
        (crash / "input.bin").write_bytes(b"AAAA")
        (crash / "sanitizer.txt").write_text(
            "ASAN_RUN_HEADER: runs=1 mode=generic testcase=output/x/scratch/x.bin started=x\n"
            "==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xdead\n"
            "READ of size 1 at 0xdead thread T0\n    #0 0xdead in app_parse sample.c:2\n"
            "SUMMARY: AddressSanitizer: heap-buffer-overflow sample.c:2 in app_parse\nCRASH_RATE: 1/1\n"
        )
        (crash / "report.md").write_text(
            f"# {crash_id}\n## Summary\nFixture.\n"
            "Trigger source: bytes\nCaller contract: obeyed\nBoundary: input file\nCaller controls: bytes\n"
        )
        return crash

    def export(self, output, crash_id):
        return subprocess.run(
            [str(EXPORT), crash_id], cwd=str(output), capture_output=True, text=True
        )

    def test_harness_reproducer_inlines_recipe_without_generic_template(self) -> None:
        output, results, source = self.make_layout("abs-test")
        sentinel = "SENTINEL_ABS_" + uuid.uuid4().hex
        self.write_recipe(source, sentinel)
        crash = self.write_crash(results, "CRASH-ABS-1")
        proc = self.export(output, crash.name)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        script = (crash / "reproduce.sh").read_text(encoding="utf-8")
        self.assertIn(sentinel, script)
        self.assertIn(".audit-build.sh", script)
        self.assertNotIn("DCMAKE_BUILD_TYPE=RelWithDebInfo", script)
        self.assertIn("AUDIT_BUILD_SCRIPT_EOF", script)

    def test_library_resolver_template_retains_canonical_suffix_fallback(self) -> None:
        source = EXPORT.read_text(encoding="utf-8")
        self.assertIn("Strip audit-side decoration", source)
        self.assertRegex(source, r"\*-asan\|\*-ubsan\|\*-msan\|\*-tsan\|\*-d\|\*-debug")

    def test_missing_recipe_warns_with_recovery_command(self) -> None:
        output, results, _source = self.make_layout("fallback-test")
        crash = self.write_crash(results, "CRASH-ABS-2")
        proc = self.export(output, crash.name)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        combined = proc.stdout + proc.stderr
        self.assertRegex(combined, r"WARN.*\.audit/build\.sh.*missing")
        self.assertRegex(combined, r"setup-target.*--build")

    def test_cli_reproducer_also_inlines_recipe_and_absolutizes_source(self) -> None:
        output, results, source = self.make_layout(
            "cli-test", build_system="autotools", asan_bin="build-asan/tool"
        )
        sentinel = "SENTINEL_CLI_" + uuid.uuid4().hex
        self.write_recipe(source, sentinel)
        crash = self.write_crash(results, "CRASH-CLI-1", harness=False)
        proc = self.export(output, crash.name)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        script = (crash / "reproduce.sh").read_text(encoding="utf-8")
        self.assertIn(sentinel, script)
        self.assertIn(".audit-build.sh", script)
        self.assertNotIn("configure --disable-shared --enable-static", script)
        self.assertRegex(script, r'src="\$\(cd "\$src" && pwd\)"')
        self.assertIn("did not inline it", EXPORT.read_text(encoding="utf-8"))

    def test_alternate_crash_inlines_captured_recipe_not_live_primary(self) -> None:
        output, results, source = self.make_layout("config-test")
        self.write_recipe(source, "PRIMARY_SENTINEL")
        crash = self.write_crash(results, "CRASH-CFG-1")
        recipe = crash / ".build-config-recipe.sh"
        recipe.write_text(
            "#!/usr/bin/env bash\nset -eu\nsrc=\"$1\"; build=\"$2\"\n"
            "mkdir -p \"$build\"\necho CONFIG_SENTINEL > \"$build/.sentinel\"\n"
        )
        (crash / ".build-config.json").write_text(json.dumps({
            "id": "wide-deadbeef00", "name": "wide",
            "recipe_sha256": hashlib.sha256(recipe.read_bytes()).hexdigest(),
        }))
        proc = self.export(output, crash.name)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        script = (crash / "reproduce.sh").read_text(encoding="utf-8")
        self.assertIn("CONFIG_SENTINEL", script)
        self.assertNotIn("PRIMARY_SENTINEL", script)

    def test_alternate_crash_rejects_changed_captured_recipe(self) -> None:
        output, results, _source = self.make_layout("config-tamper")
        crash = self.write_crash(results, "CRASH-CFG-2")
        (crash / ".build-config-recipe.sh").write_text("#!/bin/sh\necho changed\n")
        (crash / ".build-config.json").write_text(json.dumps({
            "id": "wide-deadbeef00", "name": "wide", "recipe_sha256": "0" * 64,
        }))
        proc = self.export(output, crash.name)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("different configuration", proc.stdout + proc.stderr)


if __name__ == "__main__":
    unittest.main(verbosity=2)
