"""ClusterFuzz-derived stack-trace normalization (isolated + attributed).

This module collects the parts of the crash-signature pipeline that are
copied or ported from Google's ClusterFuzz, so their provenance, license,
and re-sync points live in one place. The rest of the harness — ASan line
parsing and interesting-frame selection — lives in ``lib/stack_frames.py``
and merely calls into here.

Upstream source: https://github.com/google/clusterfuzz (branch: master)
  * ``STACK_FRAME_IGNORE_REGEXES``  — ``src/clusterfuzz/stacktraces/constants.py``
  * ``MAX_CRASH_STATE_FRAMES``      — ``src/clusterfuzz/stacktraces/constants.py``
  * ``filter_function_name``        — port of ``_filter_stack_frame``
                                      in ``src/clusterfuzz/stacktraces/__init__.py``
  * ``filter_addresses_and_numbers``— port of the same-named helper in
                                      ``src/clusterfuzz/stacktraces/__init__.py``

License: Apache License 2.0 — Copyright Google LLC.
  https://github.com/google/clusterfuzz/blob/master/LICENSE

ClusterFuzz builds a crash *state* by walking the symbolized stack, skipping
frames that match ``STACK_FRAME_IGNORE_REGEXES`` (runtime / sanitizer / libc /
fuzzer-wrapper noise) and, for each surviving frame, normalizing the function
name via ``_filter_stack_frame`` before it enters the state. The ignore check
runs against the *raw* captured name; the filter is applied *after* a frame
survives. We preserve that ordering — see ``lib/stack_frames.py``.

Local divergences from upstream are flagged with a ``# DIVERGENCE:`` marker so
they survive a re-sync. Keep them when re-pulling from upstream.
"""

from __future__ import annotations

import re


# Verbatim from ClusterFuzz ``stacktraces/constants.py`` ``STACK_FRAME_IGNORE_REGEXES``
# on master. Used for the same purpose: choose the first stack frame that is
# not sanitizer/runtime/libc/fuzzer-wrapper noise.
#
# DIVERGENCE: we also filter the libc++ (``^std::__1::``) and libstdc++
# (``^std::__cxx11::``) inline-namespace symbol prefixes. ClusterFuzz relies on
# the path-based ``.*/libc\+\+`` rule, which assumes the symbolizer emits the
# full header path. macOS' libsanitizer symbolizer strips paths and reports
# locations as bare basenames (``string:2095``, ``vector:1234``), so the path
# rule never fires and stdlib frames bubble to the top of crash signatures.
# The ``__1``/``__cxx11`` inline namespaces are only ever generated by the
# stdlib implementation, so prefix-matching them is equivalent in intent to the
# path filter. Keep this divergence when re-syncing from ClusterFuzz.
STACK_FRAME_IGNORE_REGEXES = [
    '^abort$',
    '^exit$',
    '^pthread_create$',
    '^pthread_kill$',
    '^raise$',
    '^tgkill$',
    '^__chk_fail$',
    '^__fortify_fail$',
    '^(|__)aeabi_',
    '^(|__)memcmp',
    '^(|__)memcpy',
    '^(|__)memmove',
    '^(|__)memset',
    '^(|__)strcmp',
    '^(|__)strcpy',
    '^(|__)strdup',
    '^(|__)strlen',
    '^(|__)strncpy',
    '^<null>',
    '^Abort\\(',
    '^CFCrash',
    '^ExitCallback',
    '^IsSandboxedProcess',
    '^LLVMFuzzerTestOneInput',
    '^MSanAtExitWrapper',
    '^New',
    '^RaiseException',
    '^SbSystemBreakIntoDebugger',
    '^SignalAction',
    '^SignalHandler',
    '^TestOneProtoInput',
    '^WTF::',
    '^WTFCrash',
    '^X11Error',
    '^_L_unlock_',
    '^_\\$LT\\$',
    '^__GI_',
    '^___interceptor_backtrace',
    '^__asan::',
    '^__asan_',
    '^__assert_',
    '^__cxa_atexit',
    '^__cxa_rethrow',
    '^__cxa_throw',
    '^__dump_stack',
    '^__hwasan::',
    '^__hwasan_',
    '^__interceptor_',
    '^__kasan_',
    '^__libc_',
    '^__lsan::',
    '^__lsan_',
    '^__msan::',
    '^__msan_',
    '^__pthread_kill',
    '^__run_exit_handlers',
    '^__rust_try',
    '^__sanitizer::',
    '^__sanitizer_',
    '^__tsan::',
    '^__tsan_',
    '^__ubsan::',
    '^__ubsan_',
    '^_asan_',
    '^_hwasan_',
    '^_lsan_',
    '^_msan_',
    '^_objc_terminate',
    '^_sanitizer_',
    '^_start',
    '^_tsan_',
    '^_ubsan_',
    '^abort',
    '^alloc::',
    '^android\\.app\\.ActivityManagerProxy\\.',
    '^android\\.os\\.Parcel\\.',
    '^art::Thread::CreateNativeThread',
    '^asan_',
    '^asan\\.module_ctor',
    '^asan\\.module_dtor',
    '^calloc',
    '^check_memory_region',
    '^common_exit',
    '^core::fmt::write',
    '^delete',
    '^demangling_terminate_handler',
    '^dump_backtrace',
    '^dump_stack',
    '^exit_or_terminate_process',
    '^fpehandler\\(',
    '^free',
    '^fuzzer::',
    '^g_log',
    '^generic_cpp_',
    '^gsignal',
    '^kasan_',
    '^libfuzzer_sys::initialize',
    '^main',
    '^malloc',
    '^mozalloc_',
    '^new',
    '^object_err',
    '^operator',
    '^panic_abort::',
    '^print_trailer',
    '^realloc',
    '^rust_begin_unwind',
    '^rust_fuzzer_test_input',
    '^rust_oom',
    '^rust_panic',
    '^scanf',
    '^show_stack',
    '^core::panic',
    # DIVERGENCE: allow an optional leading return type (e.g. "void
    # std::__1::allocator…", "bool std::__1::operator==<…>"); [^:(]+ stops at
    # the first '(' or '::' so this never matches into a parameter list (e.g.
    # "foo(std::__1::vector<…>)"). Pairs with the libc++ prefix note above.
    '^(?:[^:(]+\\s+)?std::__1::',
    '^(?:[^:(]+\\s+)?std::__cxx11::',
    '^std::__terminate',
    '^std::io::Write::write_fmt',
    '^std::panic',
    '^std::process::abort',
    '^std::sys::unix::abort',
    '^std::sys::backtrace',
    '^std::sys_common::backtrace',
    '^__rust_start_panic',
    '^__scrt_common_main_seh',
    # DIVERGENCE: macOS dyld tail frame. The symbolizer emits this as e.g.
    # ``start+0x1b4c`` without a source path, so the existing ``^_start``
    # rule does not catch it. Letting it through collapses unrelated CLI
    # crashes into the same dedup key.
    '^start\\+0x',
    '^libgcc_s.so.*',
    '.*ASAN_OnSIGSEGV',
    '.*BaseThreadInitThunk',
    '.*DebugBreak',
    '.*DefaultDcheckHandler',
    '.*ForceCrashOnSigAbort',
    '.*MemoryProtection::CMemoryProtector',
    '.*PartitionAlloc',
    '.*RtlFreeHeap',
    '.*RtlInitializeExceptionChain',
    '.*RtlReportCriticalFailure',
    '.*RtlUserThreadStart',
    '.*RtlpHeapHandleError',
    '.*RtlpLogHeapFailure',
    '.*SkDebugf',
    '.*StackDumpSignalHandler',
    '.*__android_log_assert',
    '.*__tmainCRTStartup',
    '.*_asan_rtl_',
    '.*agent::asan::',
    '.*allocator_shim',
    '.*asan_Heap',
    '.*asan_check_access',
    '.*asan_osx_dynamic\\.dylib',
    '.*assert',
    '.*base::FuzzedDataProvider',
    '.*base::allocator',
    '.*base::android::CheckException',
    '.*base::debug::BreakDebugger',
    '.*base::debug::CollectStackTrace',
    '.*base::debug::StackTrace::StackTrace',
    '.*ieee754\\-',
    '.*libpthread',
    '.*logger',
    '.*logging::CheckError',
    '.*logging::.*LogMessage',
    '.*logging::.*NoreturnError',
    '.*stdext::exception::what',
    '.*v8::base::OS::Abort',
    '.*Runtime_AbortCSADcheck',
    '.* base/callback',
    '.* /rust(|c)/',
    '.*/AOSP\\-toolchain/',
    '.*/bindings/ToV8\\.h',
    '.*/crosstool/',
    '.*/gcc/',
    '.*/glibc\\-',
    '.*/googletest/',
    '.*/jemalloc/',
    '.*/libc\\+\\+',
    '.*/libc/',
    '.*/llvm\\-build/',
    '.*/minkernel/crts/',
    '.*/sanitizer_common/',
    '.*/tcmalloc/',
    '.*/vc/include/',
    '.*/vctools/crt/',
    '.*/win_toolchain/',
    '.*libc\\+\\+/',
    'c:/clusterfuzz/bot/build',
    '.*third_party/fuzztest/',
    '.*/memorycmp\\.c',
    '.*\\+Unknown',
    '.*<unknown module>',
    '.*Inline Function @',
    '^<unknown>$',
    '^\\[vdso\\]$',
    '^linux-gate.so.*$',
    '^panic$',
    '^runtime\\.',
    '^CrashTrampolineAsm',
    '^libc_io_functions_not_implemented_use_fdio_instead',
    '^<libclang_rt.asan.so>',
    '^__zx_panic',
    '^syslog::LogMessage',
    '^print_address_description',
    '^_etext',
    '^_swift_stdlib_',
    '.*centipede::',
    '.*fuzztest::internal::',
    '^V8_Fatal',
    '^blink::ReportV8FatalError',
    '^v8::api_internal::ToLocalEmpty',
    '^v8::internal::Isolate::PushStackTraceAndDie',
    '^v8::internal::Isolate::PushParamsAndDie',
    '^absl::log_internal::',
    '^SkAbort_FileLine',
    '^SkMutex::~SkMutex',
]

_IGNORE_RES = [re.compile(pattern) for pattern in STACK_FRAME_IGNORE_REGEXES]

# ClusterFuzz ``stacktraces/constants.py``: the crash state is built from at
# most the top three interesting frames.
MAX_CRASH_STATE_FRAMES = 3


def matches_ignore_regexes(*haystacks: str) -> bool:
    """True if any non-empty haystack matches a STACK_FRAME_IGNORE_REGEXE.

    Callers pass the raw frame fields (function, location, raw line). Mirrors
    ClusterFuzz's ignore check, which runs against the *unfiltered* captured
    name — so this must be called before `filter_function_name`."""
    return any(
        regex.search(haystack)
        for regex in _IGNORE_RES
        for haystack in haystacks
        if haystack
    )


_ANON_NAMESPACE_PREFIXES = (
    "non-virtual thunk to ",
    "(anonymous namespace)::",
    "`anonymous namespace'::",
)
# Lsplit a function name around the first '(' or '['. The non-greedy group
# stops at the first delimiter, so it strips the parameter list and any
# `[abi:...]` / `[clone .cold]` demangler suffix while leaving template
# arguments in '<...>' intact (ClusterFuzz splits only on '(' and '[', so
# overloaded templates stay distinguishable in the crash state).
_FRAME_FILTER_RE = re.compile(r"(.*?)[\(\[].*")
# Port of the `(.*)\+([xX0-9a-fA-F]+)` fun+off split inside
# ClusterFuzz `SAN_STACK_FRAME_REGEX` (stacktraces/constants.py): a frame
# like `check_opcode_types+0xc4` is captured as `function_name` + a
# separate `function_offset` upstream, so the normalized name never carries
# the offset. We don't run the full SAN regex (the existing parser already
# handles frame splitting), so apply the same trim here at the end of
# `filter_function_name`.
_FUNC_OFFSET_RE = re.compile(r"\+[xX0-9a-fA-F]+$")


def filter_function_name(function: str) -> str:
    """Normalize a frame's function name for the crash state.

    Port of ClusterFuzz ``stacktraces._filter_stack_frame``: strip
    anonymous-namespace markers, take the segment after the last ``!``
    (``module!func``), then drop everything from the first ``(`` or ``[`` —
    the parameter list and demangler suffixes. This is what removes
    ``(unsigned int, std::__1::vector<...>)`` from a frame like
    ``Store::set_blob(unsigned int, std::__1::vector<...>)``.

    Run this only on a frame that has already survived the ignore check
    (`matches_ignore_regexes`), which matches against the raw, unfiltered
    name — mirroring ClusterFuzz's order (ignore on raw, then filter into
    the state)."""
    for ns in _ANON_NAMESPACE_PREFIXES:
        function = function.replace(ns, "")
    function = function.split("!")[-1]
    match = _FRAME_FILTER_RE.match(function)
    if match and match.group(1):
        result = match.group(1).strip()
    else:
        result = function.strip().split(" ")[0]
    return _FUNC_OFFSET_RE.sub("", result)


def filter_addresses_and_numbers(stack_frame):
    """Return a normalized string without unique addresses and numbers.

    Verbatim port of ClusterFuzz ``stacktraces.filter_addresses_and_numbers``
    (see module header for the upstream URL and license). The regexes and
    comments below are copied as-is so the address/number scrubbing — and the
    deliberate exclusions (``source.cc:1234`` line numbers, ``libfoo-1.0.so``
    version suffixes, small-integer comparisons) — stay aligned with upstream
    on re-sync."""
    # Remove offset part from end of every line.
    result = re.sub(r'\+0x[0-9a-fA-F]+\n', '\n', stack_frame, re.DOTALL)

    # Replace sections that appear to be addresses with the string "ADDRESS".
    address_expression = r'0x[a-fA-F0-9]{4,}[U]*'
    address_replacement = r'ADDRESS'
    result = re.sub(address_expression, address_replacement, result)

    # Replace sections that appear to be numbers with the string "NUMBER".
    # Cases that we are avoiding:
    # - source.cc:1234
    # - libsomething-1.0.so (to avoid things like NUMBERso in replacements)
    # - very small integer comparisons, e.g. "x >= NUMBER" for "x >= 1"
    number_expression = r'''(?<![:0-9.])          # not preceeded by any of these
                            (?:[0-9.]{4,}         # either >= 4 digits
                               |(?<=\ )[0-9]{2,}  # or >= 2 digits after space
                               |(?<=[@#])[0-9]+)  # or preceeded by @ or #
                            (?![A-Za-z0-9.])      # not followed by any of these
                            '''
    return re.sub(number_expression, 'NUMBER', result, flags=re.X)
