"""ASan stack-frame parsing and interesting-frame selection.

The ignore regex list is copied from ClusterFuzz's
``src/clusterfuzz/stacktraces/constants.py`` ``STACK_FRAME_IGNORE_REGEXES``
on master. It is used here for the same purpose: choose the first stack frame
that is not sanitizer/runtime/libc/fuzzer wrapper noise.

Local divergence: we also filter the libc++ (``^std::__1::``) and libstdc++
(``^std::__cxx11::``) inline-namespace symbol prefixes. ClusterFuzz relies on
the path-based ``.*/libc\\+\\+`` rule, which assumes the symbolizer emits the
full header path. macOS' libsanitizer symbolizer strips paths and reports
locations as bare basenames (``string:2095``, ``vector:1234``), so the path
rule never fires and stdlib frames bubble to the top of crash signatures.
The ``__1``/``__cxx11`` inline namespaces are only ever generated by the
stdlib implementation, so prefix-matching them is equivalent in intent to the
path filter. Keep this divergence when re-syncing from ClusterFuzz.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
import sys
from pathlib import Path


STACK_FRAME_IGNORE_REGEXES = [
    '^abort$',
    '^exit$',
    '^pthread_create$',
    '^pthread_kill$',
    '^raise$',
    '^tgkill$',
    '^__chk_fail$',
    '^__fortify_fail$',
    '^(|__)aeabi_',
    '^(|__)memcmp',
    '^(|__)memcpy',
    '^(|__)memmove',
    '^(|__)memset',
    '^(|__)strcmp',
    '^(|__)strcpy',
    '^(|__)strdup',
    '^(|__)strlen',
    '^(|__)strncpy',
    '^<null>',
    '^Abort\\(',
    '^CFCrash',
    '^ExitCallback',
    '^IsSandboxedProcess',
    '^LLVMFuzzerTestOneInput',
    '^MSanAtExitWrapper',
    '^New',
    '^RaiseException',
    '^SbSystemBreakIntoDebugger',
    '^SignalAction',
    '^SignalHandler',
    '^TestOneProtoInput',
    '^WTF::',
    '^WTFCrash',
    '^X11Error',
    '^_L_unlock_',
    '^_\\$LT\\$',
    '^__GI_',
    '^___interceptor_backtrace',
    '^__asan::',
    '^__asan_',
    '^__assert_',
    '^__cxa_atexit',
    '^__cxa_rethrow',
    '^__cxa_throw',
    '^__dump_stack',
    '^__hwasan::',
    '^__hwasan_',
    '^__interceptor_',
    '^__kasan_',
    '^__libc_',
    '^__lsan::',
    '^__lsan_',
    '^__msan::',
    '^__msan_',
    '^__pthread_kill',
    '^__run_exit_handlers',
    '^__rust_try',
    '^__sanitizer::',
    '^__sanitizer_',
    '^__tsan::',
    '^__tsan_',
    '^__ubsan::',
    '^__ubsan_',
    '^_asan_',
    '^_hwasan_',
    '^_lsan_',
    '^_msan_',
    '^_objc_terminate',
    '^_sanitizer_',
    '^_start',
    '^_tsan_',
    '^_ubsan_',
    '^abort',
    '^alloc::',
    '^android\\.app\\.ActivityManagerProxy\\.',
    '^android\\.os\\.Parcel\\.',
    '^art::Thread::CreateNativeThread',
    '^asan_',
    '^asan\\.module_ctor',
    '^asan\\.module_dtor',
    '^calloc',
    '^check_memory_region',
    '^common_exit',
    '^core::fmt::write',
    '^delete',
    '^demangling_terminate_handler',
    '^dump_backtrace',
    '^dump_stack',
    '^exit_or_terminate_process',
    '^fpehandler\\(',
    '^free',
    '^fuzzer::',
    '^g_log',
    '^generic_cpp_',
    '^gsignal',
    '^kasan_',
    '^libfuzzer_sys::initialize',
    '^main',
    '^malloc',
    '^mozalloc_',
    '^new',
    '^object_err',
    '^operator',
    '^panic_abort::',
    '^print_trailer',
    '^realloc',
    '^rust_begin_unwind',
    '^rust_fuzzer_test_input',
    '^rust_oom',
    '^rust_panic',
    '^scanf',
    '^show_stack',
    '^core::panic',
    # Allow an optional leading return type (e.g. "void std::__1::allocator…",
    # "bool std::__1::operator==<…>"); [^:(]+ stops at the first '(' or '::'
    # so this never matches into a parameter list (e.g. "foo(std::__1::vector<…>)").
    '^(?:[^:(]+\\s+)?std::__1::',
    '^(?:[^:(]+\\s+)?std::__cxx11::',
    '^std::__terminate',
    '^std::io::Write::write_fmt',
    '^std::panic',
    '^std::process::abort',
    '^std::sys::unix::abort',
    '^std::sys::backtrace',
    '^std::sys_common::backtrace',
    '^__rust_start_panic',
    '^__scrt_common_main_seh',
    # macOS dyld tail frame. The symbolizer emits this as e.g.
    # ``start+0x1b4c`` without a source path, so the existing ``^_start``
    # rule does not catch it. Letting it through collapses unrelated CLI
    # crashes into the same dedup key.
    '^start\\+0x',
    '^libgcc_s.so.*',
    '.*ASAN_OnSIGSEGV',
    '.*BaseThreadInitThunk',
    '.*DebugBreak',
    '.*DefaultDcheckHandler',
    '.*ForceCrashOnSigAbort',
    '.*MemoryProtection::CMemoryProtector',
    '.*PartitionAlloc',
    '.*RtlFreeHeap',
    '.*RtlInitializeExceptionChain',
    '.*RtlReportCriticalFailure',
    '.*RtlUserThreadStart',
    '.*RtlpHeapHandleError',
    '.*RtlpLogHeapFailure',
    '.*SkDebugf',
    '.*StackDumpSignalHandler',
    '.*__android_log_assert',
    '.*__tmainCRTStartup',
    '.*_asan_rtl_',
    '.*agent::asan::',
    '.*allocator_shim',
    '.*asan_Heap',
    '.*asan_check_access',
    '.*asan_osx_dynamic\\.dylib',
    '.*assert',
    '.*base::FuzzedDataProvider',
    '.*base::allocator',
    '.*base::android::CheckException',
    '.*base::debug::BreakDebugger',
    '.*base::debug::CollectStackTrace',
    '.*base::debug::StackTrace::StackTrace',
    '.*ieee754\\-',
    '.*libpthread',
    '.*logger',
    '.*logging::CheckError',
    '.*logging::.*LogMessage',
    '.*logging::.*NoreturnError',
    '.*stdext::exception::what',
    '.*v8::base::OS::Abort',
    '.*Runtime_AbortCSADcheck',
    '.* base/callback',
    '.* /rust(|c)/',
    '.*/AOSP\\-toolchain/',
    '.*/bindings/ToV8\\.h',
    '.*/crosstool/',
    '.*/gcc/',
    '.*/glibc\\-',
    '.*/googletest/',
    '.*/jemalloc/',
    '.*/libc\\+\\+',
    '.*/libc/',
    '.*/llvm\\-build/',
    '.*/minkernel/crts/',
    '.*/sanitizer_common/',
    '.*/tcmalloc/',
    '.*/vc/include/',
    '.*/vctools/crt/',
    '.*/win_toolchain/',
    '.*libc\\+\\+/',
    'c:/clusterfuzz/bot/build',
    '.*third_party/fuzztest/',
    '.*/memorycmp\\.c',
    '.*\\+Unknown',
    '.*<unknown module>',
    '.*Inline Function @',
    '^<unknown>$',
    '^\\[vdso\\]$',
    '^linux-gate.so.*$',
    '^panic$',
    '^runtime\\.',
    '^CrashTrampolineAsm',
    '^libc_io_functions_not_implemented_use_fdio_instead',
    '^<libclang_rt.asan.so>',
    '^__zx_panic',
    '^syslog::LogMessage',
    '^print_address_description',
    '^_etext',
    '^_swift_stdlib_',
    '.*centipede::',
    '.*fuzztest::internal::',
    '^V8_Fatal',
    '^blink::ReportV8FatalError',
    '^v8::api_internal::ToLocalEmpty',
    '^v8::internal::Isolate::PushStackTraceAndDie',
    '^v8::internal::Isolate::PushParamsAndDie',
    '^absl::log_internal::',
    '^SkAbort_FileLine',
    '^SkMutex::~SkMutex',
]

_IGNORE_RES = [re.compile(pattern) for pattern in STACK_FRAME_IGNORE_REGEXES]
_ASAN_FRAME_RE = re.compile(r"^\s*#(?P<index>\d+):?\s+(?:0x[0-9a-fA-F]+|[xX][0-9a-fA-F]+|<addr>)\s+(?:in\s+)?(?P<body>.+?)\s*$")
_LOC_RE = re.compile(r"(?P<loc>\S+:\d+(?::\d+)?)$")
_PATH_RE = re.compile(r"(?P<loc>\S+\.(?:c|cc|cpp|cxx|h|hh|hpp|hxx|m|mm|rs|go|java|js|ts))$")
_MODULE_RE = re.compile(r"(?P<func>.*?)\s+(?P<loc>\([^)]*(?:\+0x[0-9a-fA-F]+)?\))$")
MAX_CRASH_STATE_FRAMES = 3
STATE_STOP_MARKERS = (
    "Direct leak of",
    "Uninitialized value was stored to memory at",
    "allocated by thread",
    "created by main thread at",
    "located in stack of thread",
    "previously allocated by",
)


@dataclasses.dataclass(frozen=True)
class StackFrame:
    index: int
    function: str
    location: str
    raw: str

    @property
    def display(self) -> str:
        if self.location:
            return f"{self.function} {self.location}"
        return self.function


def _parse_frame_body(body: str) -> tuple[str, str]:
    body = body.strip()
    loc_match = _LOC_RE.search(body)
    if loc_match:
        loc = loc_match.group("loc")
        return body[:loc_match.start()].strip(), loc

    path_match = _PATH_RE.search(body)
    if path_match:
        loc = path_match.group("loc")
        return body[:path_match.start()].strip(), loc

    module_match = _MODULE_RE.match(body)
    if module_match:
        return module_match.group("func").strip(), module_match.group("loc").strip()

    return body, ""


def parse_asan_frame(line: str) -> StackFrame | None:
    match = _ASAN_FRAME_RE.match(line)
    if not match:
        return None
    function, location = _parse_frame_body(match.group("body"))
    if not function:
        return None
    return StackFrame(
        index=int(match.group("index")),
        function=function,
        location=location,
        raw=line.strip(),
    )


def is_ignored_frame(frame: StackFrame) -> bool:
    haystacks = (frame.function, frame.location, frame.raw)
    return any(regex.search(haystack) for regex in _IGNORE_RES for haystack in haystacks if haystack)


def iter_asan_frames(text: str) -> list[StackFrame]:
    frames: list[StackFrame] = []
    fallback_frames: list[StackFrame] = []
    in_report = False
    for line in text.splitlines():
        if "ERROR: AddressSanitizer" in line or "ERROR: HWAddressSanitizer" in line:
            in_report = True
            frames = []
            continue
        frame = parse_asan_frame(line)
        if not in_report:
            if frame is not None:
                fallback_frames.append(frame)
            continue
        if frames and any(marker in line for marker in STATE_STOP_MARKERS):
            break
        if line.startswith("SUMMARY: "):
            break
        if frame is not None:
            frames.append(frame)
    return frames if frames else fallback_frames


def interesting_frames(text: str, want: int = 5) -> list[StackFrame]:
    out: list[StackFrame] = []
    for frame in iter_asan_frames(text):
        if is_ignored_frame(frame):
            continue
        out.append(frame)
        if len(out) >= min(want, MAX_CRASH_STATE_FRAMES):
            break
    return out


def first_interesting_frame(text: str) -> StackFrame | None:
    frames = interesting_frames(text, want=1)
    return frames[0] if frames else None


def crash_signature(text: str, want: int = MAX_CRASH_STATE_FRAMES) -> list[str]:
    """Address-stable fingerprint for a crash.

    Returns up to `want` (function, location) lines from the top of the
    interesting-frame stream. Used by run-asan-multi to detect when reruns
    reproduce the same crash even though addresses, allocation tags, and
    thread ids differ between runs.

    Empty list = no parseable crash frames (clean run, or a non-ASan
    failure mode).
    """
    return [frame.display for frame in interesting_frames(text, want=want)]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("asan_file", type=Path)
    parser.add_argument("--first-display", action="store_true")
    parser.add_argument(
        "--signature",
        action="store_true",
        help="emit up to 3 top interesting frames (one per line) for crash matching",
    )
    args = parser.parse_args(argv)
    try:
        text = args.asan_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 1
    if args.signature:
        sig = crash_signature(text)
        # Empty output is a meaningful answer ("no crash signature"); the
        # caller distinguishes it from a missing file via exit code 0 vs 1.
        for line in sig:
            print(line)
        return 0
    frame = first_interesting_frame(text)
    if frame is None:
        return 1
    if args.first_display:
        print(frame.display)
    else:
        print(frame.raw)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
