#!/usr/bin/env bash
# lib/target_config.sh — discovery + loader for per-target config.
#
# Two files describe a target, both under output/<slug>/ (gitignored):
#
#   output/<slug>/target.toml   — static config generated by bin/setup-target
#                                 or bin/audit, then reviewed as needed. Lists
#                                 upstream URL, ASan binary/lib paths, include
#                                 dirs, link libs, build cmd.
#   output/<slug>/<backend>/results/.session-env
#                               — per-backend session captures, rewritten by
#                                 bin/audit at session start: RESULTS_DIR,
#                                 TARGET_ROOT, TARGET_SLUG, TARGET_REV.
#   output/<slug>/.session-env  — legacy compatibility copy for callers that
#                                 are not starting from a testcase path.
#
# Discovery: walk up from a starting path (testcase, CWD, or explicit dir)
# until we find a directory whose parent contains both files. Source the
# session-env, then parse target.toml into shell variables.
#
# Exposed shell vars after target_load:
#   TARGET_SLUG, TARGET_ROOT, RESULTS_DIR, TARGET_REV, SESSION_STARTED
#   TARGET_ASAN_BIN, TARGET_ASAN_LIB
#   TARGET_{UBSAN,MSAN,TSAN}_LIB (scalar; optional sanitizer-specific
#                                  static/shared library for C/C++ harnesses)
#   TARGET_INCLUDES (array), TARGET_LINK_LIBS (array)
#   TARGET_IS_BROWSER
#   TARGET_ATTACKER_CONTROLS (array; defaults to ("bytes") if [threat_model]
#                              is absent or empty)
#   TARGET_SANITIZERS_ENABLED (array; defaults to ("asan") if [sanitizer]
#                              is absent or has no valid entries)
#   TARGET_{ASAN,UBSAN,MSAN,TSAN}_SUPPRESSIONS (scalar; absolute path or empty)
#   TARGET_{ASAN,UBSAN,MSAN,TSAN}_OPTIONS (scalar; extra runtime opts or empty)
#   TARGET_{UBSAN,MSAN,TSAN}_BIN (scalar; relative or absolute path; empty
#                                  means convention-based fallback)
#   TARGET_SANITIZERS_EXPLICITLY_DISABLED (0 or 1) — set to 1 when
#                                  target.toml has [sanitizer] enabled = []
#                                  (findings-only mode for language targets
#                                  without an ASan build)
#   TARGET_RUNNER_BIN (scalar; interpreter / driver to use when no
#                       sanitizer binary is configured)
#   TARGET_RUNNER_ARGS (array; literal args, stable path tokens substituted at run)
#   TARGET_RUNNER_ENV (array; KEY=VAL pairs layered on the env)
#   TARGET_RUNNER_CRASH_PATTERNS (array; extra regex strings lib/triage.sh
#                                  uses as additional crash signals)
#
# Path semantics: asan_bin / asan_lib / includes are relative to TARGET_ROOT
# unless absolute. Relative paths may not escape TARGET_ROOT with `..`.
# target_load resolves them.
#
# TOML coverage: top-level scalars/arrays plus a single nested section per
# key (e.g. [threat_model]). Section keys are emitted as TARGET_<SECTION>_<KEY>.
# Nested tables, inline tables, and dotted keys are not supported — keep
# target.toml flat or one-section-deep.

# Resolve the path to the Python helper (this file's sibling). Functions
# below delegate parsing / discovery / seeding to lib/target_config.py.
_TARGET_CONFIG_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_TARGET_CONFIG_PY="$_TARGET_CONFIG_LIB_DIR/target_config.py"

# Initialize arrays/scalars unconditionally so callers under `set -u` can
# reference them whether or not target_load_toml has run. target_load_toml
# resets these at the top of its body on each call.
TARGET_S4_JIT_OFF=()
TARGET_S4_JIT_EAGER=()
TARGET_S6_PEERS=()
TARGET_S6_DOMAIN=""
TARGET_RUNNER_BIN=""
TARGET_RUNNER_ARGS=()
TARGET_RUNNER_ENV=()
TARGET_RUNNER_CRASH_PATTERNS=()
TARGET_SANITIZERS_EXPLICITLY_DISABLED=0

target_die() {
  echo "[target] $*" >&2
  return 1
}

# Walk up from $1 looking for the nearest .session-env. Testcase paths prefer
# output/<slug>/<backend>/results/.session-env so concurrent backends do not
# race through the legacy output/<slug>/.session-env copy.
# Returns the session dir path on success.
target_find_session_dir() {
  local start="${1:-$PWD}"
  python3 "$_TARGET_CONFIG_PY" find-session-dir "$start"
}

# Source session-env from a slug dir.
target_load_session_env() {
  local slug_dir="$1"
  local env_file="$slug_dir/.session-env"
  [ -f "$env_file" ] || target_die "session-env not found: $env_file" || return 1
  # Python helper emits `export KEY='value'` lines for the allowlisted keys
  # (RESULTS_DIR, TARGET_ROOT, TARGET_SLUG, TARGET_REV, SESSION_STARTED,
  # LOGDIR) with single-quote escaping safe to eval.
  local _export_lines
  _export_lines=$(python3 "$_TARGET_CONFIG_PY" read-session-env "$slug_dir") || return 1
  eval "$_export_lines"
}

# TOML parsing delegates to lib/target_config.py (uses stdlib tomllib for
# real-TOML correctness). The Python helper emits the same NUL-delimited
# KEY\0VALUE\0... stream the bash loader has always consumed, so the
# downstream target_load_toml shape is unchanged. See lib/target_config.py
# for the legacy stream format and section/key handling.
_target_parse_toml() {
  local file="$1"
  python3 "$_TARGET_CONFIG_PY" parse-toml "$file"
}

# Canonical set of attacker_controls tokens. Anything outside this set
# is logged on stderr and dropped — silently accepting typos would
# weaken the verdict matrix in lib/triage.sh.
TARGET_ATTACKER_CONTROLS_VALID=("bytes" "call-sequence" "call-order" "timing" "race" "env" "protocol-state" "fs-state")

# Canonical sanitizer slugs. Same dropped-with-warning policy as
# attacker_controls — silently accepting typos would let an audit
# silently run only ASan when the operator thought MSan was on.
# 'race' is the Go runtime race detector; it produces "WARNING: DATA RACE"
# output that lib/triage.sh recognizes as a crash signal.
TARGET_SANITIZERS_VALID=("asan" "ubsan" "msan" "tsan" "race")

_target_sanitizer_is_valid() {
  local v="$1" ok
  for ok in "${TARGET_SANITIZERS_VALID[@]}"; do
    [ "$v" = "$ok" ] && return 0
  done
  return 1
}

_target_normalize_attacker_control() {
  # Lowercase + map call-order → call-sequence (synonym used in reports).
  local v="$1"
  v=$(printf '%s' "$v" | tr '[:upper:]' '[:lower:]')
  case "$v" in
    call-order) v="call-sequence" ;;
  esac
  printf '%s' "$v"
}

_target_attacker_control_is_valid() {
  local v="$1" ok
  for ok in "${TARGET_ATTACKER_CONTROLS_VALID[@]}"; do
    [ "$v" = "$ok" ] && return 0
  done
  return 1
}

# Parse target.toml and set globals.
target_load_toml() {
  local file="$1"
  [ -f "$file" ] || target_die "target.toml not found: $file" || return 1
  local _parsed
  _parsed="$(mktemp "${TMPDIR:-/tmp}/target-toml-XXXXXX")" || return 1
  if ! _target_parse_toml "$file" > "$_parsed"; then
    rm -f "$_parsed"
    return 1
  fi
  TARGET_INCLUDES=()
  TARGET_DEFINES=()
  TARGET_LINK_LIBS=()
  TARGET_ATTACKER_CONTROLS=()
  TARGET_SANITIZERS_ENABLED=()
  TARGET_SANITIZERS_EXPLICITLY_DISABLED=0
  TARGET_ASAN_BIN=""
  TARGET_ASAN_LIB=""
  TARGET_UBSAN_BIN=""
  TARGET_MSAN_BIN=""
  TARGET_TSAN_BIN=""
  TARGET_UBSAN_LIB=""
  TARGET_MSAN_LIB=""
  TARGET_TSAN_LIB=""
  TARGET_ASAN_SUPPRESSIONS=""
  TARGET_UBSAN_SUPPRESSIONS=""
  TARGET_MSAN_SUPPRESSIONS=""
  TARGET_TSAN_SUPPRESSIONS=""
  TARGET_ASAN_OPTIONS=""
  TARGET_UBSAN_OPTIONS=""
  TARGET_MSAN_OPTIONS=""
  TARGET_TSAN_OPTIONS=""
  TARGET_IS_BROWSER=0
  TARGET_S4_JIT_OFF=()
  TARGET_S4_JIT_EAGER=()
  TARGET_S6_PEERS=()
  TARGET_S6_DOMAIN=""
  TARGET_RUNNER_BIN=""
  TARGET_RUNNER_ARGS=()
  TARGET_RUNNER_ENV=()
  TARGET_RUNNER_CRASH_PATTERNS=()
  # Track whether [sanitizer].enabled was seen at all. The legacy parser
  # emitted TARGET_SANITIZER_ENABLED_LIST whenever the array was present
  # — even when empty — so we set the flag on first sight of that key.
  local _sanitizer_enabled_seen=0
  local key val
  # Use NUL-delimited stream so values can have spaces.
  while IFS= read -r -d '' key && IFS= read -r -d '' val; do
    case "$key" in
      TARGET_SLUG_VAL|TARGET_TARGET) : ;;  # target name is supplied by session env
      TARGET_ASAN_BIN)            TARGET_ASAN_BIN="$val" ;;
      TARGET_ASAN_LIB)            TARGET_ASAN_LIB="$val" ;;
      TARGET_IS_BROWSER)          TARGET_IS_BROWSER="$val" ;;
      TARGET_INCLUDES_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_INCLUDES+=("$line")
        done <<< "$val"
        ;;
      TARGET_DEFINES_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_DEFINES+=("$line")
        done <<< "$val"
        ;;
      TARGET_LINK_LIBS_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_LINK_LIBS+=("$line")
        done <<< "$val"
        ;;
      TARGET_THREAT_MODEL_ATTACKER_CONTROLS_LIST)
        while IFS= read -r line; do
          [ -z "$line" ] && continue
          local norm
          norm=$(_target_normalize_attacker_control "$line")
          if _target_attacker_control_is_valid "$norm"; then
            TARGET_ATTACKER_CONTROLS+=("$norm")
          else
            target_die "ignored unknown attacker_controls token in $file: '$line' (valid: ${TARGET_ATTACKER_CONTROLS_VALID[*]})" || true
          fi
        done <<< "$val"
        ;;
      TARGET_SANITIZER_ENABLED_LIST)
        _sanitizer_enabled_seen=1
        while IFS= read -r line; do
          [ -z "$line" ] && continue
          local norm
          norm=$(printf '%s' "$line" | tr '[:upper:]' '[:lower:]')
          if _target_sanitizer_is_valid "$norm"; then
            TARGET_SANITIZERS_ENABLED+=("$norm")
          else
            target_die "ignored unknown sanitizer in $file: '$line' (valid: ${TARGET_SANITIZERS_VALID[*]})" || true
          fi
        done <<< "$val"
        ;;
      TARGET_SANITIZER_ASAN_SUPPRESSIONS)  TARGET_ASAN_SUPPRESSIONS="$val" ;;
      TARGET_SANITIZER_UBSAN_SUPPRESSIONS) TARGET_UBSAN_SUPPRESSIONS="$val" ;;
      TARGET_SANITIZER_MSAN_SUPPRESSIONS)  TARGET_MSAN_SUPPRESSIONS="$val" ;;
      TARGET_SANITIZER_TSAN_SUPPRESSIONS)  TARGET_TSAN_SUPPRESSIONS="$val" ;;
      TARGET_SANITIZER_ASAN_OPTIONS)       TARGET_ASAN_OPTIONS="$val" ;;
      TARGET_SANITIZER_UBSAN_OPTIONS)      TARGET_UBSAN_OPTIONS="$val" ;;
      TARGET_SANITIZER_MSAN_OPTIONS)       TARGET_MSAN_OPTIONS="$val" ;;
      TARGET_SANITIZER_TSAN_OPTIONS)       TARGET_TSAN_OPTIONS="$val" ;;
      TARGET_SANITIZER_UBSAN_BIN)          TARGET_UBSAN_BIN="$val" ;;
      TARGET_SANITIZER_MSAN_BIN)           TARGET_MSAN_BIN="$val" ;;
      TARGET_SANITIZER_TSAN_BIN)           TARGET_TSAN_BIN="$val" ;;
      TARGET_SANITIZER_UBSAN_LIB)          TARGET_UBSAN_LIB="$val" ;;
      TARGET_SANITIZER_MSAN_LIB)           TARGET_MSAN_LIB="$val" ;;
      TARGET_SANITIZER_TSAN_LIB)           TARGET_TSAN_LIB="$val" ;;
      TARGET_S4_DIFF_PAIRS_JIT_OFF_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_S4_JIT_OFF+=("$line")
        done <<< "$val"
        ;;
      TARGET_S4_DIFF_PAIRS_JIT_EAGER_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_S4_JIT_EAGER+=("$line")
        done <<< "$val"
        ;;
      TARGET_S6_PEERS_PEERS_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_S6_PEERS+=("$line")
        done <<< "$val"
        ;;
      TARGET_S6_PEERS_DOMAIN)
        TARGET_S6_DOMAIN="$val"
        ;;
      TARGET_RUNNER_BIN)
        TARGET_RUNNER_BIN="$val"
        ;;
      TARGET_RUNNER_ARGS_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_RUNNER_ARGS+=("$line")
        done <<< "$val"
        ;;
      TARGET_RUNNER_ENV_LIST)
        while IFS= read -r line; do
          # Must contain '=' to be a valid env binding; silently drop the rest.
          case "$line" in *=*) TARGET_RUNNER_ENV+=("$line") ;; esac
        done <<< "$val"
        ;;
      TARGET_RUNNER_CRASH_PATTERNS_LIST)
        while IFS= read -r line; do
          [ -n "$line" ] && TARGET_RUNNER_CRASH_PATTERNS+=("$line")
        done <<< "$val"
        ;;
    esac
  done < "$_parsed"
  rm -f "$_parsed"

  # Default threat model when [threat_model] is absent: pure bytes-in.
  # This is the right default for parsers/decoders/codecs and keeps
  # legacy target.toml files working without modification.
  if [ "${#TARGET_ATTACKER_CONTROLS[@]}" -eq 0 ]; then
    TARGET_ATTACKER_CONTROLS=("bytes")
  fi
  # Default sanitizer policy: ASan only — UNLESS the operator explicitly
  # set `[sanitizer].enabled = []` (findings-only mode for interpreted-
  # language targets without an ASan build). MSan/UBSan/TSan/race are
  # opt-in per target. The "section was seen and empty" case sets
  # TARGET_SANITIZERS_EXPLICITLY_DISABLED=1; legacy targets without any
  # [sanitizer] section keep the historical ASan default.
  if [ "${#TARGET_SANITIZERS_ENABLED[@]}" -eq 0 ]; then
    if [ "$_sanitizer_enabled_seen" -eq 1 ]; then
      TARGET_SANITIZERS_EXPLICITLY_DISABLED=1
    else
      TARGET_SANITIZERS_ENABLED=("asan")
    fi
  fi
}

# Return 0 if the active target has at least one sanitizer enabled. Useful
# for runners that want to skip ASAN_OPTIONS injection when running a
# sanitizer-less ([sanitizer] enabled = []) target.
target_has_any_sanitizer() {
  [ "${#TARGET_SANITIZERS_ENABLED[@]}" -gt 0 ] && return 0
  return 1
}

# Print the Swift compiler sanitizer spelling for a harness sanitizer slug.
target_swift_sanitizer_flag() {
  case "${1:-}" in
    asan)  printf '%s\n' "address" ;;
    ubsan) printf '%s\n' "undefined" ;;
    tsan)  printf '%s\n' "thread" ;;
    *)
      target_die "Swift runner does not support sanitizer '${1:-<unset>}' (supported: asan, ubsan, tsan)" || return 1
      ;;
  esac
}

target_runner_tokens_supported() {
  local sanitizer="${1:-${PROBE_SANITIZER_SELECTED:-}}" v
  for v in "${TARGET_RUNNER_ARGS[@]:-}" "${TARGET_RUNNER_ENV[@]:-}"; do
    case "$v" in
      *"{SWIFT_SANITIZER}"*) target_swift_sanitizer_flag "$sanitizer" >/dev/null || return 1 ;;
    esac
  done
}

# Expand stable path/runtime tokens in a single runner string, printing the
# result on stdout. Values are still passed as literal argv/KEY=VAL entries;
# this only substitutes audit-owned paths so generated target.toml files stay
# relocatable. {TESTCASE} expands to the second argument (empty for env), and
# sanitizer tokens derive from the third argument or PROBE_SANITIZER_SELECTED.
target_expand_runner_tokens() {
  local v="$1" testcase="${2:-}" sanitizer="${3:-${PROBE_SANITIZER_SELECTED:-}}" swift_sanitizer=""
  if [[ "$v" == *"{SWIFT_SANITIZER}"* ]]; then
    swift_sanitizer="$(target_swift_sanitizer_flag "$sanitizer")" || return 1
  fi
  v="${v//\{TESTCASE\}/$testcase}"
  v="${v//\{SANITIZER\}/$sanitizer}"
  v="${v//\{SWIFT_SANITIZER\}/$swift_sanitizer}"
  v="${v//\{TARGET_ROOT\}/${TARGET_ROOT:-}}"
  v="${v//\{RESULTS_DIR\}/${RESULTS_DIR:-}}"
  v="${v//\{TARGET_SLUG\}/${TARGET_SLUG:-}}"
  printf '%s\n' "$v"
}

# Substitute stable tokens ("{TESTCASE}", "{TARGET_ROOT}", "{SANITIZER}", …) in
# every element of TARGET_RUNNER_ARGS, printing the result one-per-line on stdout.
target_runner_args_for_testcase() {
  local testcase="$1" sanitizer="${2:-${PROBE_SANITIZER_SELECTED:-}}" a
  for a in "${TARGET_RUNNER_ARGS[@]:-}"; do
    [ -n "$a" ] || continue
    target_expand_runner_tokens "$a" "$testcase" "$sanitizer" || return 1
  done
}

# Expand stable runner tokens in TARGET_RUNNER_ENV. Values are still passed as
# literal KEY=VAL entries to `env`; this helper only substitutes audit-owned
# paths so generated target.toml files can stay relocatable.
target_runner_env_expanded() {
  local sanitizer="${1:-${PROBE_SANITIZER_SELECTED:-}}" e
  for e in "${TARGET_RUNNER_ENV[@]:-}"; do
    [ -n "$e" ] || continue
    target_expand_runner_tokens "$e" "" "$sanitizer" || return 1
  done
}

# Return 0 if `name` (asan|ubsan|msan|tsan) is in the enabled list.
target_sanitizer_is_enabled() {
  local name="$1" s
  [ -n "$name" ] || return 1
  for s in "${TARGET_SANITIZERS_ENABLED[@]}"; do
    [ "$s" = "$name" ] && return 0
  done
  return 1
}

# Print absolute path to the suppression file for `name` (asan|ubsan|msan|tsan),
# or nothing if no suppression is configured. Does NOT check existence — the
# runner prints a warning if the file is missing.
target_sanitizer_suppressions_path() {
  local name="$1" raw=""
  case "$name" in
    asan)  raw="$TARGET_ASAN_SUPPRESSIONS" ;;
    ubsan) raw="$TARGET_UBSAN_SUPPRESSIONS" ;;
    msan)  raw="$TARGET_MSAN_SUPPRESSIONS" ;;
    tsan)  raw="$TARGET_TSAN_SUPPRESSIONS" ;;
    *)     return 1 ;;
  esac
  [ -z "$raw" ] && return 0
  target_resolve_path "$raw"
}

# Print extra runtime options to append to *_OPTIONS for `name`, or empty.
target_sanitizer_extra_options() {
  local name="$1"
  case "$name" in
    asan)  printf '%s' "$TARGET_ASAN_OPTIONS" ;;
    ubsan) printf '%s' "$TARGET_UBSAN_OPTIONS" ;;
    msan)  printf '%s' "$TARGET_MSAN_OPTIONS" ;;
    tsan)  printf '%s' "$TARGET_TSAN_OPTIONS" ;;
    *)     return 1 ;;
  esac
}

# Print the configured library path for a C/C++ harness built under `name`.
# ASan's historical top-level `asan_lib` stays unchanged for compatibility;
# non-ASan harness builds use optional [sanitizer].<name>_lib entries.
target_sanitizer_lib_path() {
  local name="$1" raw=""
  case "$name" in
    asan)  raw="${TARGET_ASAN_LIB:-}" ;;
    ubsan) raw="${TARGET_UBSAN_LIB:-}" ;;
    msan)  raw="${TARGET_MSAN_LIB:-}" ;;
    tsan)  raw="${TARGET_TSAN_LIB:-}" ;;
    *)     return 1 ;;
  esac
  [ -z "$raw" ] && return 0
  target_resolve_path "$raw"
}

# Emit clang argv that embeds DT_RUNPATH (ELF) / LC_RPATH (Mach-O) for the
# directory holding the resolved sanitizer library, so a linked harness
# self-locates its companion shared lib at exec time. Static archives get
# the entry too — the loader never consults it without a shared dep, so
# it's a no-op. Empty output when no library is configured.
#
# Shared with bin/export-repro's reproduce.sh template (san_lib_dir): both
# converge on `${lib%/*}` as the rpath directory. Keep these in sync.
target_sanitizer_rpath_args() {
  local lib="$1"
  [ -n "$lib" ] || return 0
  case "$lib" in
    */*) printf '%s\n' "-Wl,-rpath,${lib%/*}" ;;
    *)   return 0 ;;
  esac
}

# Print TARGET_SANITIZERS_ENABLED as a CSV string, in declared order, with
# duplicates removed. Empty array prints "asan" UNLESS the operator
# explicitly set `[sanitizer].enabled = []` (TARGET_SANITIZERS_EXPLICITLY_DISABLED=1),
# in which case the helper prints an empty string — the signal that the
# target is in findings-only mode.
target_sanitizers_enabled_csv() {
  if [ "${#TARGET_SANITIZERS_ENABLED[@]}" -eq 0 ]; then
    if [ "${TARGET_SANITIZERS_EXPLICITLY_DISABLED:-0}" = "1" ]; then
      printf '\n'
      return 0
    fi
    printf 'asan\n'
    return 0
  fi
  local out="" v seen=":"
  for v in "${TARGET_SANITIZERS_ENABLED[@]}"; do
    case "$seen" in *:"$v":*) continue ;; esac
    seen="${seen}${v}:"
    [ -n "$out" ] && out="${out},"
    out="${out}${v}"
  done
  printf '%s\n' "$out"
}

# Print TARGET_ATTACKER_CONTROLS as a CSV string, in declared order, with
# duplicates removed. Empty array prints "bytes" (matches the loader default).
target_attacker_controls_csv() {
  if [ "${#TARGET_ATTACKER_CONTROLS[@]}" -eq 0 ]; then
    printf 'bytes\n'
    return 0
  fi
  local out="" v seen=":"
  for v in "${TARGET_ATTACKER_CONTROLS[@]}"; do
    case "$seen" in *:"$v":*) continue ;; esac
    seen="${seen}${v}:"
    [ -n "$out" ] && out="${out},"
    out="${out}${v}"
  done
  printf '%s\n' "$out"
}

# Resolve an asan_bin / asan_lib / include path relative to TARGET_ROOT.
# Inside a container AUDIT_BUILD_SUFFIX is set; bare build-{san}/ prefixes
# get the suffix appended so target.toml stays portable between host and
# per-image container builds. Literally pre-suffixed paths pass through.
target_resolve_path() {
  local p="$1"
  [ -n "$p" ] || { printf '\n'; return 0; }
  case "$p" in
    /*) printf '%s\n' "$p"; return 0 ;;
    ..|../*|*/..|*/../*)
        target_die "relative target path escapes TARGET_ROOT: $p" || return 1 ;;
  esac
  if [ -n "${AUDIT_BUILD_SUFFIX:-}" ]; then
    local head="${p%%/*}"
    case "$head" in
      build-asan|build-ubsan|build-msan|build-tsan)
        p="${head}${AUDIT_BUILD_SUFFIX}${p#${head}}" ;;
    esac
  fi
  printf '%s/%s\n' "$TARGET_ROOT" "$p"
}

target_output_sanitize_experiment() {
  local raw
  raw=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alnum:]._-' '-')
  raw="${raw#-}"
  raw="${raw%-}"
  [ -n "$raw" ] || target_die "experiment name resolved to empty string" || return 1
  printf '%s\n' "$raw"
}

target_output_slug() {
  local slug experiment suffix
  if [ $# -ge 1 ]; then slug="$1"; else slug="${TARGET_SLUG:-}"; fi
  if [ $# -ge 2 ]; then experiment="$2"; else experiment="${AUDIT_EXPERIMENT_NAME:-}"; fi
  if [ $# -ge 3 ]; then suffix="$3"; else suffix="${AUDIT_EXPERIMENT_SUFFIX:-}"; fi
  [ -n "$slug" ] || target_die "target slug is required for output path" || return 1
  if [ -n "$suffix" ]; then
    printf '%s%s\n' "$slug" "$suffix"
  elif [ -n "$experiment" ]; then
    printf '%s-%s\n' "$slug" "$(target_output_sanitize_experiment "$experiment")"
  else
    printf '%s\n' "$slug"
  fi
}

target_output_root() {
  local argc="$#"
  local script_root slug experiment suffix
  if [ $# -ge 1 ]; then script_root="$1"; else script_root="${SCRIPT_ROOT:-}"; fi
  if [ $# -ge 2 ]; then slug="$2"; else slug="${TARGET_SLUG:-}"; fi
  if [ $# -ge 3 ]; then experiment="$3"; else experiment="${AUDIT_EXPERIMENT_NAME:-}"; fi
  if [ $# -ge 4 ]; then suffix="$4"; else suffix="${AUDIT_EXPERIMENT_SUFFIX:-}"; fi
  local output_slug="${TARGET_OUTPUT_SLUG:-}"
  [ -n "$script_root" ] || target_die "SCRIPT_ROOT is required for output path" || return 1
  # >1 args means a slug was passed explicitly and may differ from the
  # cached TARGET_OUTPUT_SLUG, so recompute; with 0-1 args reuse the cache.
  if [ "$argc" -gt 1 ] || [ -z "$output_slug" ]; then
    output_slug=$(target_output_slug "$slug" "$experiment" "$suffix") || return 1
  fi
  printf '%s/output/%s\n' "$script_root" "$output_slug"
}

target_backend_results_dir() {
  local backend="$1"
  shift || true
  [ -n "$backend" ] || target_die "backend is required for results path" || return 1
  printf '%s/%s/results\n' "$(target_output_root "$@")" "$backend"
}

target_backend_logs_dir() {
  local backend="$1"
  shift || true
  [ -n "$backend" ] || target_die "backend is required for logs path" || return 1
  printf '%s/%s/logs\n' "$(target_output_root "$@")" "$backend"
}

# Derive output/<slug>[-<experiment>]/target.toml from a backend RESULTS_DIR
# (output/<slug>[-<experiment>]/<backend>/results — target.toml is always two
# levels up). The target.toml need not exist yet; callers test for it.
target_toml_from_results() {
  local results="${1:-${RESULTS_DIR:-}}" dir
  [ -n "$results" ] || return 1
  dir=$(cd "$results/../.." 2>/dev/null && pwd) || return 1
  printf '%s/target.toml\n' "$dir"
}

# Derive target.toml from either a legacy output/<slug> session dir or a
# backend-local output/<slug>/<backend>/results session dir.
target_toml_from_session_dir() {
  local session_dir="$1" dir
  [ -n "$session_dir" ] || return 1
  case "$session_dir" in
    */results)
      dir=$(cd "$session_dir/../.." 2>/dev/null && pwd) || return 1
      printf '%s/target.toml\n' "$dir"
      return 0 ;;
  esac
  printf '%s/target.toml\n' "$session_dir"
}

# One-shot loader: discover + source + parse. Pass an optional starting
# path (defaults to PWD).
target_load() {
  local start="${1:-$PWD}"
  local slug_dir toml_path
  if ! slug_dir=$(target_find_session_dir "$start"); then
    target_die "no output/<slug>/.session-env found above: $start (run bin/audit first, or pass --target)" || return 1
  fi
  target_load_session_env "$slug_dir" || return 1
  toml_path="$(target_toml_from_session_dir "$slug_dir")" || {
    target_die "target.toml not found for session dir: $slug_dir" || return 1
  }
  target_load_toml "$toml_path" || return 1
}

# Write a fresh .session-env. Caller passes slug_dir, RESULTS_DIR,
# TARGET_ROOT, TARGET_SLUG, TARGET_REV, LOGDIR.
target_write_session_env() {
  local slug_dir="$1" results="$2" target_root="$3" slug="$4" rev="$5" logdir="$6"
  python3 "$_TARGET_CONFIG_PY" write-session-env \
    "$slug_dir" "$results" "$target_root" "$slug" "${rev:-unknown}" "$logdir"
}

# Detect whether TARGET_ROOT is its own git/hg checkout or a plain source tree.
target_detect_repo_type() {
  python3 "$_TARGET_CONFIG_PY" detect-repo-type "$1"
}

# Probe a TARGET_ROOT for the current git/hg HEAD revision. Plain source trees
# use the sentinel "norev"; missing paths stay empty.
target_detect_rev() {
  python3 "$_TARGET_CONFIG_PY" detect-rev "$1"
}

# Seed a starter target.toml by introspecting TARGET_ROOT. Best-effort:
# generated placeholders are reviewed after the build exists.
target_seed_toml() {
  python3 "$_TARGET_CONFIG_PY" seed-toml "$1" "$2" "${3:-}"
}

# Re-seed but carry curated [threat_model]/[s6_peers] forward — used for a
# placeholder refresh so filling one FILL_ME never discards hand/LLM-curated
# sections a fresh seed cannot re-derive.
target_seed_toml_preserving() {
  python3 "$_TARGET_CONFIG_PY" seed-toml "$1" "$2" "${3:-}" --preserve-curated
}
