#!/usr/bin/env python3
"""lib/target_config.py — discovery + loader for per-target config.

Two files describe a target under output/<slug>/ (gitignored):

  output/<slug>/target.toml   — static config generated by bin/setup-target or
                                bin/audit, then reviewed as needed.
  output/<slug>/<backend>/results/.session-env
                              — per-backend session captures, rewritten by
                                bin/audit at session start. A legacy
                                output/<slug>/.session-env may also exist for
                                callers that are not starting from a testcase.

Two interfaces:

1. Python API (for python callers like bin/export-repro):
       cfg = target_config.load(start_path)
       cfg.target_root, cfg.includes, cfg.attacker_controls, ...

2. Subcommand CLI (for the bash shim in lib/target_config.sh):
       python3 lib/target_config.py parse-toml <file>
       python3 lib/target_config.py seed-toml <root> <out> [url]
       python3 lib/target_config.py detect-repo-type <root>
       python3 lib/target_config.py detect-rev <root>
       python3 lib/target_config.py find-session-dir [<start>]
       python3 lib/target_config.py read-session-env <slug_dir>
       python3 lib/target_config.py write-session-env <args...>
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import shlex
import subprocess
import sys
import tempfile
try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None
from dataclasses import dataclass, field
from datetime import datetime, timezone

# Single source of truth for language-aware data (runner blocks,
# extensions, harness dispatch, bootstrap commands). Imported as
# `languages` for the rest of this module.
import languages
from pathlib import Path
from typing import Iterable, Optional

NO_REV = "norev"

# Revision / URL sentinels meaning "no usable upstream was recorded" — a
# local-only target, or a checkout with no VCS, or an un-seeded target.toml.
# Single source of truth for the report and link builders (bin/export-repro,
# lib/report_enrich) so they agree on what is worth a "clones upstream@<rev>"
# hint or a /blob/<rev>/ source link. Mirrors lib/benchmark._hash_text.
#
# "HEAD" is deliberately NOT unpinned: it clones and resolves to a forge's
# default branch, so a target with a real upstream but no recorded commit
# still gets a working hint/link. The only cost is a non-permalink line ref,
# which is strictly more useful to a maintainer than no link at all.
_UNPINNED_REVS = frozenset({"", NO_REV, "no-vcs", "unknown", "?"})
_PLACEHOLDER_URLS = frozenset({"", "fill_me"})


def is_unpinned_rev(rev: str) -> bool:
    """True when `rev` is a sentinel meaning 'no usable upstream commit'.

    `HEAD` is treated as usable (returns False) — see `_UNPINNED_REVS`."""
    return (rev or "").strip().lower() in _UNPINNED_REVS


def is_placeholder_url(url: str) -> bool:
    """True when `url` is empty or the un-seeded target.toml `FILL_ME` stub."""
    return (url or "").strip().lower() in _PLACEHOLDER_URLS


def config_has_live_placeholder(toml_path: "str | os.PathLike") -> bool:
    """True when target.toml has an UNRESOLVED placeholder a re-seed can fix —
    an active (parsed, non-comment) field whose value still contains FILL_ME.

    bin/setup-target uses this to decide whether to refresh a generated config.
    Two things are deliberately NOT treated as placeholders, so a reviewed
    config keeps the operator's edits across reruns instead of being rewritten:

      * commented example lines such as `# ubsan_lib = "build-<san>/FILL_ME.a"`,
        which the seed always emits and the TOML parser never sees; and
      * `upstream_url = "FILL_ME"` on a local-only target (unpinned pinned_rev),
        which is the intended steady state — re-seeding cannot resolve it.

    A grep for FILL_ME cannot make these distinctions (it matches comments and
    the local-only upstream), which is why this parses the TOML instead.
    """
    try:
        parsed = parse_toml(Path(toml_path))
    except Exception:
        return False  # unparsable config is handled by the caller's own check
    upstream_unresolvable = is_unpinned_rev(str(parsed.get("pinned_rev", "") or ""))

    def _walk(obj, key=None) -> bool:
        if isinstance(obj, str):
            if "FILL_ME" not in obj:
                return False
            return not (key == "upstream_url" and upstream_unresolvable)
        if isinstance(obj, dict):
            return any(_walk(v, k) for k, v in obj.items())
        if isinstance(obj, list):
            return any(_walk(v, key) for v in obj)
        return False

    return _walk(parsed)

# TOML basic-string escaping. Used everywhere we write a Python string
# into a generated target.toml so an unsanitised value (a tainted slug,
# an LLM-suggested peer name with an embedded quote, a Windows-style
# regex with backslashes) cannot break the file. Mirrors the TOML 1.0
# spec's escape table; anything outside basic ASCII / above 0x7E is
# emitted as a \uXXXX sequence so editors render the output sanely.
_TOML_BASIC_ESCAPES = {
    "\\": "\\\\",
    '"':  '\\"',
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
}


def toml_basic_string(value: str) -> str:
    """Render `value` as a TOML basic-string literal (including the quotes).

    Escapes backslash, double-quote, the control-character set TOML calls
    out by name, and anything else below 0x20 / equal to 0x7F as a \\uXXXX
    sequence. Non-strings are stringified first so callers can pass through
    arbitrary scalar metadata without a TypeError.
    """
    if not isinstance(value, str):
        value = "" if value is None else str(value)
    out: list[str] = ['"']
    for ch in value:
        esc = _TOML_BASIC_ESCAPES.get(ch)
        if esc is not None:
            out.append(esc)
            continue
        code = ord(ch)
        if code < 0x20 or code == 0x7F:
            out.append(f"\\u{code:04X}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def toml_comment_lines(text: str) -> str:
    """Render arbitrary text as TOML comment(s), one line per source line.

    Every line (split on \\n / \\r\\n / \\r) is prefixed with "# " so a
    multi-line LLM reasoning blob cannot escape the comment context and
    turn second-line content into active TOML. Empty input collapses to
    a single bare "#" so the surrounding layout is preserved.
    """
    if text is None:
        return "#"
    s = str(text)
    if not s:
        return "#"
    lines = s.splitlines() or [""]
    return "\n".join("# " + line for line in lines)


# Canonical attacker_controls tokens. Anything outside this set is logged on
# stderr and dropped (silent acceptance would weaken lib/triage.sh's verdict
# matrix). Order matches lib/target_config.sh:TARGET_ATTACKER_CONTROLS_VALID.
ATTACKER_CONTROLS_VALID = (
    "bytes", "call-sequence", "call-order", "timing",
    "race", "env", "protocol-state", "fs-state",
)

# Canonical sanitizer slugs. Only ASan is enabled by default; the rest must be
# opted in per target via [sanitizer].enabled because MSan needs the whole
# dependency tree instrumented, and UBSan/TSan benefit from triage-aware
# suppression files. Go's race detector ("race") is wired in for Go targets —
# it emits "WARNING: DATA RACE" reports that lib/triage.sh treats as
# diagnostic signal. Anything outside this set is logged on stderr and dropped.
SANITIZERS_VALID = ("asan", "ubsan", "msan", "tsan", "race")

# .session-env keys we trust to import into the parent shell environment.
SESSION_ENV_ALLOW = (
    "RESULTS_DIR", "TARGET_ROOT", "TARGET_SLUG",
    "TARGET_REV", "TARGET_REPO_TYPE", "SESSION_STARTED", "LOGDIR",
)

# Section/key names emitted as shell variables must restrict to [A-Za-z0-9_]
# so they're safe to splice into TARGET_<SECTION>_<KEY>. The legacy parser
# used this to discard invalid section headers; default parsing is now strict
# and only uses the legacy behavior when TARGET_TOML_LENIENT=1.
_SHELL_NAME_RE = re.compile(r"^[A-Za-z0-9_]+$")


def _normalize_attacker_control(v: str) -> str:
    v = v.lower()
    if v == "call-order":
        v = "call-sequence"
    return v


def _is_valid_attacker_control(v: str) -> bool:
    return v in ATTACKER_CONTROLS_VALID


def _strip_bad_section_headers(text: str) -> str:
    """Drop `[<name>]` headers whose name has chars outside [A-Za-z0-9_].

    Mirrors the bash parser, which silently absorbed bad sections and let
    the keys after them fall back to top-level. Real TOML would error on
    `[bad section name with spaces]`; this preserves the lenient behavior.
    """
    out_lines = []
    section_re = re.compile(r"^\s*\[([^\]]*)\]\s*(?:#.*)?$")
    for line in text.splitlines(keepends=True):
        m = section_re.match(line.rstrip("\n"))
        if m:
            name = m.group(1).strip()
            if not name or not _SHELL_NAME_RE.match(name):
                # Drop the header — keys that follow go to the previous
                # (or top-level) scope. Replace with blank to keep line
                # numbers stable for any future error messages.
                out_lines.append("\n")
                continue
        out_lines.append(line)
    return "".join(out_lines)


def _toml_value_to_str(v) -> str:
    """Render a scalar TOML value the way the bash parser produced it.

    Strings come through as-is. Bools/ints/floats render as their Python
    str() form. The bash parser only emitted strings, so any non-string
    scalar in target.toml is a behavior change (loud, not silent).
    """
    if isinstance(v, str):
        return v
    if isinstance(v, bool):
        return "1" if v else "0"
    return str(v)


class _FallbackTOMLDecodeError(ValueError):
    pass


def _strip_inline_comment(line: str) -> str:
    in_quote = False
    escaped = False
    for i, ch in enumerate(line):
        if escaped:
            escaped = False
            continue
        if ch == "\\" and in_quote:
            escaped = True
            continue
        if ch == '"':
            in_quote = not in_quote
            continue
        if ch == "#" and not in_quote:
            return line[:i]
    return line


def _split_array_items(body: str) -> list[str]:
    items: list[str] = []
    start = 0
    in_quote = False
    escaped = False
    for i, ch in enumerate(body):
        if escaped:
            escaped = False
            continue
        if ch == "\\" and in_quote:
            escaped = True
            continue
        if ch == '"':
            in_quote = not in_quote
            continue
        if ch == "," and not in_quote:
            items.append(body[start:i].strip())
            start = i + 1
    if in_quote:
        raise _FallbackTOMLDecodeError("unterminated quoted array item")
    items.append(body[start:].strip())
    return items


def _array_literal_is_closed(value: str) -> bool:
    in_quote = False
    escaped = False
    for ch in value:
        if escaped:
            escaped = False
            continue
        if ch == "\\" and in_quote:
            escaped = True
            continue
        if ch == '"':
            in_quote = not in_quote
            continue
        if ch == "]" and not in_quote:
            return True
    return False


def _parse_basic_string(value: str) -> str:
    out: list[str] = []
    i = 0
    escapes = {
        "b": "\b",
        "t": "\t",
        "n": "\n",
        "f": "\f",
        "r": "\r",
        '"': '"',
        "\\": "\\",
    }
    while i < len(value):
        ch = value[i]
        if ch != "\\":
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= len(value):
            raise _FallbackTOMLDecodeError("unterminated string escape")
        esc = value[i]
        if esc in escapes:
            out.append(escapes[esc])
            i += 1
            continue
        if esc in ("u", "U"):
            n = 4 if esc == "u" else 8
            code = value[i + 1:i + 1 + n]
            if len(code) != n or not re.match(r"^[0-9A-Fa-f]+$", code):
                raise _FallbackTOMLDecodeError(f"invalid unicode escape: \\{esc}{code}")
            out.append(chr(int(code, 16)))
            i += 1 + n
            continue
        raise _FallbackTOMLDecodeError(f"unsupported string escape: \\{esc}")
    return "".join(out)


def _parse_array_value(val: str) -> list[str]:
    if not (val.startswith("[") and val.endswith("]")):
        raise _FallbackTOMLDecodeError(f"unsupported TOML array: {val}")
    body = val[1:-1].strip()
    if body == "":
        return []
    items = []
    for part in _split_array_items(body):
        item = part.strip()
        if item == "":
            continue
        if len(item) >= 2 and item[0] == item[-1] == '"':
            items.append(_parse_basic_string(item[1:-1]))
        else:
            raise _FallbackTOMLDecodeError(f"unsupported TOML array item: {part}")
    return items


def _parse_simple_toml(text: str) -> dict:
    parsed: dict = {}
    current = parsed
    section_re = re.compile(r"^\s*\[([A-Za-z0-9_-]+)\]\s*$")
    scalar_re = re.compile(r'^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$')

    raw_lines = text.splitlines()
    i = 0
    while i < len(raw_lines):
        raw_line = raw_lines[i]
        i += 1
        line = _strip_inline_comment(raw_line).strip()
        if not line:
            continue
        sec = section_re.match(line)
        if sec:
            current = parsed.setdefault(sec.group(1), {})
            continue
        m = scalar_re.match(line)
        if not m:
            raise _FallbackTOMLDecodeError(f"unsupported TOML line: {raw_line}")
        key, val = m.groups()
        val = val.strip()
        if val.startswith("["):
            while not _array_literal_is_closed(val):
                if i >= len(raw_lines):
                    raise _FallbackTOMLDecodeError(f"unterminated TOML array for key: {key}")
                val += "\n" + _strip_inline_comment(raw_lines[i]).strip()
                i += 1
            current[key] = _parse_array_value(val)
        elif len(val) >= 2 and val[0] == val[-1] == '"':
            current[key] = _parse_basic_string(val[1:-1])
        elif val.lower() in ("true", "false"):
            current[key] = val.lower() == "true"
        else:
            current[key] = val
    return parsed


def parse_toml(path: str | os.PathLike) -> dict:
    """Parse a target.toml.

    Strict TOML parsing is the default. Set TARGET_TOML_LENIENT=1 only for
    migration of legacy local configs that relied on the old bash parser's
    behavior of ignoring invalid section headers.
    """
    with open(path, "rb") as f:
        raw = f.read()
    text = raw.decode("utf-8", errors="replace")
    if os.environ.get("TARGET_TOML_LENIENT") == "1":
        pre = _strip_bad_section_headers(text)
    else:
        pre = text
    if tomllib is not None:
        return tomllib.loads(pre)
    return _parse_simple_toml(pre)


def _emit_legacy_stream(parsed: dict) -> bytes:
    """Emit the NUL-delimited KEY\\0VALUE\\0... stream consumed by the
    bash target_load_toml loop.

    Output keys match the bash parser exactly:
      top-level scalar foo  -> TARGET_FOO\\0value\\0
      top-level array  foo  -> TARGET_FOO_LIST\\0joined\\0  (entries \\n-terminated)
      [section] scalar bar  -> TARGET_<SECTION>_BAR\\0value\\0
      [section] array  bar  -> TARGET_<SECTION>_BAR_LIST\\0joined\\0
    """
    out = bytearray()

    def emit_scalar(key: str, value: str) -> None:
        out.extend(key.encode("utf-8"))
        out.append(0)
        out.extend(value.encode("utf-8"))
        out.append(0)

    def emit_list(key: str, items: list) -> None:
        joined = ""
        for item in items:
            if isinstance(item, str):
                joined += item + "\n"
            else:
                joined += _toml_value_to_str(item) + "\n"
        out.extend(key.encode("utf-8"))
        out.append(0)
        out.extend(joined.encode("utf-8"))
        out.append(0)

    def visit(d: dict, prefix: str) -> None:
        for k, v in d.items():
            if not _SHELL_NAME_RE.match(k):
                # Section or key with chars unsafe for shell-var splicing
                # — preserve bash behavior of silently dropping it.
                continue
            shell_key = f"{prefix}{k.upper()}"
            if isinstance(v, dict):
                # Single nested section per key, e.g. [threat_model].
                # Bash parser flattens to TARGET_<SECTION>_<KEY>.
                visit(v, f"{shell_key}_")
            elif isinstance(v, list):
                emit_list(f"{shell_key}_LIST", v)
            else:
                emit_scalar(shell_key, _toml_value_to_str(v))

    visit(parsed, "TARGET_")
    return bytes(out)


# ─── Discovery ──────────────────────────────────────────────────────

def find_session_dir(start: str | os.PathLike) -> Optional[Path]:
    """Walk up from `start` looking for the nearest .session-env.

    Testcases live under output/<slug>/<backend>/results/scratch-N, so the
    nearest backend-local results/.session-env wins and avoids cross-backend
    races. For legacy/manual callers outside a results tree, also scan
    output/<slug>/.session-env and output/<slug>/<backend>/results/.session-env
    below each ancestor.
    """
    p = Path(start)
    if not p.exists():
        p = Path.cwd()
    if not p.is_dir():
        p = p.parent
    try:
        cur = p.resolve()
    except OSError:
        return None
    def scan_output_tree(base: Path) -> Optional[Path]:
        out_dir = base / "output"
        if not out_dir.is_dir():
            return None
        try:
            targets = sorted(out_dir.iterdir())
        except OSError:
            return None
        for target in targets:
            if not target.is_dir():
                continue
            # Backend-local output/<slug>/<backend>/results/.session-env is
            # authoritative; prefer it over the legacy output/<slug>/
            # .session-env copy, which concurrent backends race on.
            try:
                backends = sorted(target.iterdir())
            except OSError:
                backends = []
            for backend in backends:
                cand = backend / "results"
                if cand.is_dir() and (cand / ".session-env").is_file():
                    return cand
            if (target / ".session-env").is_file():
                return target
        return None

    while True:
        if (cur / ".session-env").is_file():
            return cur
        found = scan_output_tree(cur)
        if found is not None:
            return found
        if cur.parent == cur:
            return None
        cur = cur.parent


def target_toml_for_session_dir(session_dir: str | os.PathLike) -> Path:
    """Return target.toml for a legacy slug dir or backend results dir."""
    d = Path(session_dir)
    # output/<slug>/<backend>/results/.session-env -> output/<slug>/target.toml
    if d.name == "results":
        return d.parent.parent / "target.toml"
    return d / "target.toml"


def find_slug_session_dir(slug_dir: str | os.PathLike) -> Optional[Path]:
    """Resolve the session dir for a known output/<slug> directory.

    `find_session_dir` walks *up* from an arbitrary path; this resolves
    the other direction — caller already knows the slug dir and wants its
    .session-env. A backend-local output/<slug>/<backend>/results/
    .session-env is authoritative and wins over the legacy
    output/<slug>/.session-env copy (which concurrent backends race on).
    With several backends present the lexicographically-first is returned
    so the choice is deterministic. Returns None when neither exists.
    """
    d = Path(slug_dir)
    if d.is_dir():
        for backend in sorted(d.iterdir()):
            if not backend.is_dir():
                continue
            cand = backend / "results"
            if (cand / ".session-env").is_file():
                return cand
    if (d / ".session-env").is_file():
        return d
    return None


# ─── .session-env ──────────────────────────────────────────────────

def read_session_env(slug_dir: str | os.PathLike) -> dict[str, str]:
    """Read .session-env, returning the allowlisted KEY -> value map."""
    env_file = Path(slug_dir) / ".session-env"
    if not env_file.is_file():
        raise FileNotFoundError(f"session-env not found: {env_file}")
    out: dict[str, str] = {}
    with open(env_file, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            key, _, value = line.partition("=")
            if key in SESSION_ENV_ALLOW:
                out[key] = value
    return out


def write_session_env(
    slug_dir: str | os.PathLike,
    results: str,
    target_root: str,
    slug: str,
    rev: str,
    logdir: str,
) -> None:
    """Write a fresh .session-env (matches target_write_session_env)."""
    d = Path(slug_dir)
    d.mkdir(parents=True, exist_ok=True)
    started = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rev_v = rev or "unknown"
    # Persist the VCS type so downstream tools (e.g. bin/reachability) get the
    # authoritative decision from resumable state without re-resolving the
    # target root from output-path heuristics. Detected from the same
    # target_root the audit binds, so it cannot disagree with bin/audit.
    try:
        repo_type = detect_repo_type(target_root)
    except Exception:
        repo_type = "none"
    lines = [
        "# Written by bin/audit at session start. Sourced by bin/probe and friends.",
        f"RESULTS_DIR={results}",
        f"TARGET_ROOT={target_root}",
        f"TARGET_SLUG={slug}",
        f"TARGET_REV={rev_v}",
        f"TARGET_REPO_TYPE={repo_type}",
        f"LOGDIR={logdir}",
        f"SESSION_STARTED={started}",
    ]
    tmp_name = ""
    env_path = d / ".session-env"
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=d,
            prefix=".session-env.",
            suffix=".tmp",
            delete=False,
        ) as f:
            tmp_name = f.name
            f.write("\n".join(lines) + "\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_name, env_path)
        # Best-effort directory fsync so the rename is durable. Both the
        # open and the fsync can fail on filesystems that do not support
        # syncing a directory fd (some networked / sandboxed mounts) — the
        # rename itself already landed, so a failure here must not abort
        # the caller (this runs at audit session start).
        try:
            fd = os.open(str(d), os.O_RDONLY)
        except OSError:
            return
        try:
            os.fsync(fd)
        except OSError:
            pass
        finally:
            os.close(fd)
    finally:
        if tmp_name:
            try:
                os.unlink(tmp_name)
            except FileNotFoundError:
                pass


# ─── git/hg/plain source detection ──────────────────────────────────

def detect_repo_type(target_root: str | os.PathLike) -> str:
    """Return git, hg, or none for a target checkout.

    A target nested under the harness repo is still a plain target unless it
    has direct VCS metadata. That avoids treating targets/foo as a git
    checkout only because /work/.git exists above it.
    """
    root = Path(target_root)
    if (root / ".hg").is_dir():
        return "hg"
    if not (root / ".git").exists():
        return "none"
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--git-dir"],
            capture_output=True, text=True, timeout=10,
        )
        if out.returncode == 0:
            return "git"
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "none"


def detect_rev(target_root: str | os.PathLike) -> str:
    root = Path(target_root)
    repo_type = detect_repo_type(root)
    if repo_type == "git":
        try:
            out = subprocess.run(
                ["git", "-C", str(root), "rev-parse", "HEAD"],
                capture_output=True, text=True, timeout=10,
            )
            if out.returncode == 0:
                return out.stdout.strip()
        except (OSError, subprocess.TimeoutExpired):
            pass
        return ""

    if repo_type == "hg":
        try:
            out = subprocess.run(
                ["hg", "--cwd", str(root), "id", "-i"],
                capture_output=True, text=True, timeout=10,
            )
            if out.returncode == 0:
                return out.stdout.strip().rstrip("+")
        except (OSError, subprocess.TimeoutExpired):
            pass
        return ""

    if (root / ".git").exists():
        return ""

    if root.is_dir():
        return NO_REV
    return ""


# ─── Seed a starter target.toml ─────────────────────────────────────

_BROWSER_SLUGS = {"firefox", "chromium", "webkit", "servo"}
_BROWSER_BIN_CANDIDATES = (
    "dist/Nightly.app/Contents/MacOS/firefox",
    "dist/bin/firefox",
)

# CMake `install(TARGETS ...)` keywords that terminate the target-name list.
# Anything after one of these is install configuration, not a target name.
_CMAKE_INSTALL_KEYWORDS = frozenset({
    "EXPORT", "ARCHIVE", "LIBRARY", "RUNTIME", "OBJECTS", "FRAMEWORK", "BUNDLE",
    "PRIVATE_HEADER", "PUBLIC_HEADER", "RESOURCE", "INCLUDES", "DESTINATION",
    "PERMISSIONS", "CONFIGURATIONS", "COMPONENT", "NAMELINK_COMPONENT",
    "NAMELINK_ONLY", "NAMELINK_SKIP", "OPTIONAL", "EXCLUDE_FROM_ALL",
    "FILE_SET", "TYPE", "CXX_MODULES_BMI",
})


def _manifest_texts(target_root: Path, filename: str, max_depth: int = 3) -> list[str]:
    """Return the text of every `filename` within `max_depth` of target_root.

    Bounded walk: prunes sanitizer build trees, VCS dirs and dependency
    caches so a seed-time scan never descends an entire source checkout.
    """
    texts: list[str] = []
    root_str = str(target_root)
    for dirpath, dirnames, filenames in os.walk(target_root):
        depth = dirpath[len(root_str):].count(os.sep)
        if depth >= max_depth:
            dirnames[:] = []
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith(("build-", ".")) and d != "node_modules"
        ]
        if filename in filenames:
            try:
                texts.append(
                    Path(dirpath, filename).read_text(
                        encoding="utf-8", errors="replace")
                )
            except OSError:
                pass
    return texts


def _autotools_installed_programs(texts: Iterable[str]) -> list[str]:
    """Names from `bin_PROGRAMS` / `sbin_PROGRAMS` in automake Makefile.am text.

    Only the *installed* program primaries are read — `check_PROGRAMS` and
    `noinst_PROGRAMS` (test drivers, helpers) are deliberately excluded.
    """
    decl_re = re.compile(r"^\s*(?:bin|sbin)_PROGRAMS\s*[+:]?=\s*(.*)$")
    out: list[str] = []
    for text in texts:
        # Collapse automake backslash line-continuations first.
        joined = re.sub(r"\\\n", " ", text)
        for line in joined.splitlines():
            m = decl_re.match(line)
            if m:
                out.extend(m.group(1).split())
    return out


def _cmake_installed_executables(texts: Iterable[str]) -> list[str]:
    """Executable target names a CMake project *installs*.

    Collects `add_executable(<name> ...)` declarations and the target list
    of `install(TARGETS ...)`, then returns their intersection so test-only
    executables (declared but not installed) are not picked. Falls back to
    every declared executable when no resolvable install() target list is
    found — still derived from the tree, never a hardcoded list.
    """
    text_list = list(texts)
    exec_names: set[str] = set()
    add_exec_re = re.compile(
        r"add_executable\s*\(\s*([A-Za-z0-9_.-]+)", re.IGNORECASE)
    for text in text_list:
        for m in add_exec_re.finditer(text):
            exec_names.add(m.group(1))
    if not exec_names:
        return []
    install_re = re.compile(
        r"install\s*\(\s*TARGETS\b([^)]*)\)", re.IGNORECASE | re.DOTALL)
    installed: list[str] = []
    for text in text_list:
        for m in install_re.finditer(text):
            for tok in m.group(1).split():
                if tok.upper() in _CMAKE_INSTALL_KEYWORDS:
                    break
                if tok in exec_names:
                    installed.append(tok)
    return installed or sorted(exec_names)


def _meson_executables(texts: Iterable[str]) -> list[str]:
    """First (name) argument of every `executable(...)` call in meson.build."""
    exe_re = re.compile(
        r"\bexecutable\s*\(\s*(?:'([^']+)'|\"([^\"]+)\")", re.IGNORECASE)
    out: list[str] = []
    for text in texts:
        for m in exe_re.finditer(text):
            out.append(m.group(1) or m.group(2))
    return out


def declared_cli_names(target_root: str | os.PathLike, build_system: str) -> list[str]:
    """User-facing CLI program names the target's own build manifests declare.

    Derived at runtime from the live target tree — never a hardcoded
    per-project list, which would couple the shared harness to specific
    codebases under audit. `seed_toml` uses this only to bias its asan_bin
    guess toward the project's installed CLI when build-asan/ holds several
    instrumented executables; the free executable scan remains the fallback
    when this yields nothing (unknown build system, generated names, ...).
    """
    root = Path(target_root)
    if build_system == "autotools":
        raw = _autotools_installed_programs(_manifest_texts(root, "Makefile.am"))
    elif build_system == "cmake":
        raw = _cmake_installed_executables(_manifest_texts(root, "CMakeLists.txt"))
    elif build_system == "meson":
        raw = _meson_executables(_manifest_texts(root, "meson.build"))
    else:
        raw = []
    names: list[str] = []
    seen: set[str] = set()
    for tok in raw:
        # Strip autotools $(EXEEXT) adornment and surrounding quotes.
        tok = tok.replace("$(EXEEXT)", "").strip().strip("'\"")
        if not tok or tok in seen:
            continue
        # Reject unresolved build-system variable references and anything
        # that is not a plain program name.
        if not re.fullmatch(r"[A-Za-z0-9._-]+", tok):
            continue
        seen.add(tok)
        names.append(tok)
    return names

# ─── S4 differential pair taxonomy ──────────────────────────────────
#
# Per-engine CLI flag sets for differential JIT execution. Each engine has
# its own toggle vocabulary; flag names are years-stable so per-target
# metadata in target.toml is the right home. seed_toml writes these
# defaults into [s4_diff_pairs] when --new-target seeds a browser-target
# config; the operator can override.
#
# Keys:
#   jit_off       — flags that disable the optimizing JIT (interpreter / baseline only)
#   jit_eager     — flags that force the optimizing JIT to engage as early as possible
#
# Validation: `<shell> --help | grep <flag>` confirms availability. If the
# engine renames a flag, the runner reports unknown-flag at startup —
# loud failure, not silent miss.
_S4_DIFF_PAIRS_TAXONOMY: dict[str, dict[str, list[str]]] = {
    "firefox": {
        "jit_off": ["--no-ion"],
        "jit_eager": ["--ion-eager"],
    },
    "chromium": {
        # V8 d8: disable both optimizing tiers; force-promote with --always-turbofan.
        "jit_off": ["--no-turbofan", "--no-maglev"],
        "jit_eager": ["--always-turbofan"],
    },
    "webkit": {
        # JSC: --useJIT=false drops to LLInt interpreter. Eager side warms
        # baseline immediately; full FTL still tier-ups on heat in practice.
        "jit_off": ["--useJIT=false"],
        "jit_eager": ["--thresholdForJITAfterWarmUp=0"],
    },
    "servo": {
        # Servo embeds SpiderMonkey — same flags as firefox.
        "jit_off": ["--no-ion"],
        "jit_eager": ["--ion-eager"],
    },
}


def s4_diff_pairs_for(slug: str) -> dict[str, list[str]]:
    """Return the default [s4_diff_pairs] table for `slug`, or {} if unknown."""
    return {k: list(v) for k, v in _S4_DIFF_PAIRS_TAXONOMY.get(slug, {}).items()}


# ─── Threat-model seed lookup (reads .agents/references/threat_models.toml) ──
#
# The per-target threat-model seed table is operator-curated reference data,
# not shared-harness logic — keeping a per-project dict literal in lib/ would
# violate the target-agnostic rule. It lives in .agents/references/, the same
# home as the S6 peers table, and is read at seed time. Unknown non-browser
# targets fall back to the conservative byte-only default; browser targets
# share one structural threat model keyed off is_browser (not a project list).

def _threat_models_toml_path() -> Path:
    """Resolve .agents/references/threat_models.toml relative to this file."""
    return (
        Path(__file__).resolve().parent.parent
        / ".agents" / "references" / "threat_models.toml"
    )


def threat_model_for(slug: str,
                     threat_models_path: Path | None = None) -> list[str]:
    """Return the curated default attacker_controls for `slug`, or [] if none.

    Reads .agents/references/threat_models.toml (or the override path for
    testing). An empty list means the slug has no curated entry — the caller
    falls back to the byte-only default. Malformed/missing file degrades to
    [] so seeding still proceeds.
    """
    path = threat_models_path if threat_models_path is not None else _threat_models_toml_path()
    if not path.is_file():
        return []
    try:
        parsed = parse_toml(str(path))
    except Exception:
        return []
    entry = parsed.get(slug)
    if not isinstance(entry, dict):
        return []
    controls = entry.get("attacker_controls", [])
    if not isinstance(controls, list):
        return []
    return [c for c in controls if isinstance(c, str) and c]


def attacker_controls_for_seed(slug: str, is_browser: bool,
                               threat_models_path: Path | None = None) -> list[str]:
    """Return default [threat_model].attacker_controls for a seeded target.

    Browser targets share one structural threat model. Non-browser targets
    use the operator-curated seed from .agents/references/threat_models.toml,
    falling back to the conservative byte-only default when no entry exists.
    """
    if is_browser:
        return ["bytes", "call-sequence", "timing"]
    curated = threat_model_for(slug, threat_models_path)
    return curated if curated else ["bytes"]


# Runtime symbol each sanitizer's instrumentation links into an executable.
# `nm` reveals them; their presence confirms the binary is actually
# instrumented (not a stray host tool that landed in the build tree).
_SANITIZER_RUNTIME_MARKER = {
    "asan": "__asan_", "ubsan": "__ubsan_", "msan": "__msan_", "tsan": "__tsan_",
}


def _binary_uses_sanitizer(path: Path, sanitizer: str = "asan") -> bool:
    marker = _SANITIZER_RUNTIME_MARKER.get(sanitizer, "__asan_")
    try:
        out = subprocess.run(
            ["nm", str(path)], capture_output=True, text=True, timeout=20,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    if out.returncode != 0:
        return False
    return marker in out.stdout


def _find_under(asan_dir: Path, *, name: str | None = None,
                maxdepth: int = 3) -> list[Path]:
    """Equivalent to: find <asan_dir> -maxdepth <n> -type f [-name <name>]."""
    if not asan_dir.is_dir():
        return []
    out: list[Path] = []

    def walk(d: Path, depth: int) -> None:
        if depth > maxdepth:
            return
        try:
            entries = sorted(d.iterdir())
        except OSError:
            return
        for e in entries:
            if e.is_file():
                if name is None or e.name == name:
                    out.append(e)
            elif e.is_dir() and not e.is_symlink():
                walk(e, depth + 1)

    walk(asan_dir, 1)
    return out


def _is_shared_lib(name: str) -> bool:
    """A linkable shared object: lib<name>.so / .dylib, or a versioned
    SONAME (lib<name>.so.2, lib<name>.2.dylib)."""
    return name.endswith((".so", ".dylib")) or ".so." in name


# Build subdirectories that hold artifacts which are never the audited
# project's own library or CLI: CMake's CMakeFiles/ (compiler-probe
# binaries like CMakeDetermineCompilerABI_C.bin, object trees), unit-test
# frameworks vendored under test(s)/ (Unity, gtest, …), and FetchContent
# dependency builds under _deps/. Inclusion criterion: a directory a build
# system populates with helper/probe/dependency artifacts, not the target's
# primary output. Structural (no project names), target-agnostic as new
# projects appear.
_AUX_BUILD_DIRS = {"cmakefiles", "test", "tests", "_deps"}


def _is_aux_build_path(p: Path, base_dir: Path) -> bool:
    try:
        rel = p.relative_to(base_dir)
    except ValueError:
        return False
    return any(part.lower() in _AUX_BUILD_DIRS for part in rel.parts[:-1])


def _path_has_aux_component(rel_path: str) -> bool:
    """True if a target.toml-relative path string traverses a build-internal
    aux directory — used to recognise a stale/bogus <san>_bin/<san>_lib value
    (e.g. a CMakeFiles compiler probe) that detection should scrub."""
    return any(part.lower() in _AUX_BUILD_DIRS
               for part in rel_path.replace("\\", "/").split("/"))


def _pick_shared_lib(san_dir: Path, root: Path) -> str:
    """Best shared library to link a C harness against, when the build
    emits no static archive (the cmake/meson default for c-ares, pcre2,
    …). Prefer the canonical unversioned linker name (libfoo.so,
    libfoo.dylib) over its versioned SONAME siblings (libfoo.so.2,
    libfoo.2.19.4.dylib); among equals, shortest basename then path.

    Single-library convention, mirroring the static-archive heuristic
    above: ambiguous multi-library builds resolve to the first canonical
    match, which the operator can override in target.toml."""
    shared = [s for s in _find_under(san_dir, name=None)
              if _is_shared_lib(s.name) and "posix" not in s.name
              and not _is_aux_build_path(s, san_dir)]
    if not shared:
        return ""
    shared.sort(key=lambda s: (not s.name.endswith((".so", ".dylib")),
                               len(s.name), str(s)))
    return str(shared[0]).removeprefix(str(root) + "/")


def _detect_sanitizer_lib(san_dir: Path, root: Path) -> str:
    """Library a C harness must link against for the sanitizer built under
    `san_dir` (a build-<san>/ tree). Static archive preferred (the harness
    links it directly); otherwise the canonical instrumented shared object.
    Empty when the build tree is absent or ships no linkable library —
    i.e. a header-only library or a CLI-only target. Sanitizer-agnostic:
    the same archive-then-shared rule holds for asan/ubsan/msan/tsan."""
    if not san_dir.is_dir():
        return ""
    archives = [a for a in _find_under(san_dir, name=None)
                if a.suffix == ".a" and not _is_aux_build_path(a, san_dir)]
    for a in archives[:3]:
        if "posix" in a.name:
            continue
        return str(a).removeprefix(str(root) + "/")
    if archives:
        return str(archives[0]).removeprefix(str(root) + "/")
    return _pick_shared_lib(san_dir, root)


def _detect_cli_bin(san_dir: Path, root: Path, build_system: str,
                    sanitizer: str = "asan") -> str:
    """Best instrumented CLI executable under `san_dir` (a build-<san>/
    tree): a declared CLI name from the build manifests first, else the
    first instrumented executable that is not a shared library, object file,
    or build-system-internal artifact (CMakeFiles/ compiler probes, test
    helpers). Empty when the build ships no CLI — a library-only or
    header-only target. The aux-dir prune is what stops a CMake compiler
    probe (CMakeDetermineCompilerABI_C.bin) being mistaken for the tool."""
    if not san_dir.is_dir():
        return ""
    for cand_name in declared_cli_names(root, build_system):
        for m in _find_under(san_dir, name=cand_name):
            if (os.access(m, os.X_OK) and not _is_aux_build_path(m, san_dir)
                    and _binary_uses_sanitizer(m, sanitizer)):
                return str(m).removeprefix(str(root) + "/")
    # Filter to plausible CLI executables BEFORE capping the nm probes:
    # CMakeFiles/ alone can hold dozens of files, so capping first would
    # exhaust the budget on pruned entries and never reach the real tool
    # (e.g. curl's build puts src/curl after a large CMakeFiles/ tree).
    def _is_cli_candidate(f: Path) -> bool:
        if _is_aux_build_path(f, san_dir) or not os.access(f, os.X_OK):
            return False
        return not (f.name.endswith((".exe", ".so", ".dylib", ".o"))
                    or "sanity" in f.name)
    candidates = [f for f in _find_under(san_dir) if _is_cli_candidate(f)]
    for f in candidates[:60]:
        if _binary_uses_sanitizer(f, sanitizer):
            return str(f).removeprefix(str(root) + "/")
    return ""


def refresh_detected_build_fields(target_root: Path, toml_path: Path) -> bool:
    """Re-detect <san>_bin and <san>_lib for every sanitizer from the build
    trees now on disk and correct them in target.toml in place. Policy per
    field: when the build yields a value, adopt it (filling an unset field
    or replacing a stale one); when it does not, scrub a value that points
    at a build-internal artifact (a CMake compiler probe, a test-framework
    archive) or a now-missing path, and otherwise leave the field — and
    every curated section — untouched. Returns True if anything changed.

    seed_toml must run before any build exists (it supplies build_system to
    the build step), so on a fresh target it cannot detect these fields and
    leaves them commented FILL_ME; on a target rebuilt under different cmake
    options a previously-detected path can also go stale. setup-target
    calls this after materializing the canonical build to repair that
    ordering — a surgical line edit, not a re-seed, so the LLM-curated
    [threat_model]/[s6_peers] survive."""
    if target_root.name in _BROWSER_SLUGS:
        return False  # browsers use fixed bin candidates; no harness lib link
    suffix = os.environ.get("AUDIT_BUILD_SUFFIX", "")
    build_system = _detect_build_system(target_root)
    try:
        lines = Path(toml_path).read_text(encoding="utf-8").splitlines()
    except OSError:
        return False
    changed = False

    def _value_of(line: str) -> str:
        if line.lstrip().startswith("#"):
            return ""
        m = re.search(r'=\s*"((?:[^"\\]|\\.)*)"', line)
        return m.group(1) if m else ""

    def _active(field: str, value: str) -> str:
        # asan_* keep seed's wide alignment; the rest use the [sanitizer]
        # block's short form. Cosmetic — the TOML parser ignores spacing.
        if field in ("asan_bin", "asan_lib"):
            return f"{field}{' ' * (14 - len(field))}= {toml_basic_string(value)}"
        pad = " " * (len("ubsan_lib") - len(field))
        return f"{field}{pad} = {toml_basic_string(value)}"

    def _commented(field: str, san: str) -> str:
        # Retain FILL_ME so bin/setup-target's grep-for-FILL_ME re-seed
        # trigger keeps firing for the now-unset field.
        stem = "FILL_ME.a" if field.endswith("_lib") else "FILL_ME"
        return f'# {field} = "build-{san}{suffix}/{stem}"'

    def _refresh(field: str, san: str, detected: str) -> None:
        nonlocal changed
        field_re = re.compile(rf"^\s*#?\s*{field}\b\s*=")
        for i, ln in enumerate(lines):
            if not field_re.match(ln):
                continue
            cur = _value_of(ln)
            cur_bogus = bool(cur) and (
                _path_has_aux_component(cur)
                or not (target_root / cur).exists()
            )
            if detected:
                new_line = _active(field, detected)      # fill or correct
            elif cur_bogus:
                new_line = _commented(field, san)        # scrub stale/bogus
            else:
                return                                   # leave good or unset
            if new_line != ln:
                lines[i] = new_line
                changed = True
            return

    for san in ("asan", "ubsan", "msan", "tsan"):
        san_dir = target_root / f"build-{san}{suffix}"
        _refresh(f"{san}_lib", san, _detect_sanitizer_lib(san_dir, target_root))
        _refresh(f"{san}_bin", san,
                 _detect_cli_bin(san_dir, target_root, build_system, san))
    if changed:
        Path(toml_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return changed


_HEADER_SUFFIXES = (".h", ".hpp", ".hh", ".hxx", ".H")


def _detect_include_dirs(target_root: Path, asan_dir_name: str) -> list[str]:
    """Return public-header search paths relative to target_root.

    Heuristic, not exhaustive — covers the layouts the seeder has observed:
      - `include/` populated with headers (curl, libxml2, openssl, ...)
      - headers at source root (cJSON, sqlite, lua, libpng, ...)
      - `src/` carrying public headers (some autotools projects)
    The `build-asan/include` entry is always emitted because CMake/Meson
    routinely generate config headers there; if the dir doesn't exist at
    repro time the -I just does nothing.
    """
    out: list[str] = []

    def _has_headers(d: Path, recursive: bool = False) -> bool:
        if not d.is_dir():
            return False
        try:
            it = d.rglob("*") if recursive else d.iterdir()
            for e in it:
                if e.is_file() and e.suffix in _HEADER_SUFFIXES:
                    return True
        except OSError:
            pass
        return False

    if _has_headers(target_root / "include", recursive=True):
        out.append("include")
    if _has_headers(target_root, recursive=False):
        out.append(".")
    # `src/` is a public-header location for some autotools projects but a
    # private-only one for many others; only include it when it actually
    # has headers AND no `include/` was found, to avoid pulling private
    # internals onto the search path for projects that already publish via
    # `include/`.
    if "include" not in out and _has_headers(target_root / "src", recursive=False):
        out.append("src")
    out.append(f"{asan_dir_name}/include")
    return out


def _detect_build_system(target_root: Path) -> str:
    """Return a slug naming the dominant build/package system at target_root.

    The slug drives both `seed_toml`'s default [runner] block and
    `bin/export-repro`'s reproduce.sh template. Order matters: native-build
    systems are checked before language-ecosystem package managers because
    a polyglot tree may have Cargo+autotools (e.g. a Rust binding inside a
    C library) — the native build is the one ASan ties into.
    """
    # Native compiled systems (driver scripts first, then build files).
    if (target_root / "mach").is_file() and os.access(target_root / "mach", os.X_OK):
        return "mach"
    if (target_root / "CMakeLists.txt").is_file():
        return "cmake"
    if (target_root / "meson.build").is_file():
        return "meson"
    if (
        (target_root / "configure").is_file() and os.access(target_root / "configure", os.X_OK)
        or (target_root / "configure.ac").is_file()
        or (target_root / "autogen.sh").is_file()
    ):
        return "autotools"
    # Language ecosystems — single canonical manifest per language. The
    # order here matters only when a tree has multiple manifests; the
    # first match wins. We pick the language whose runtime is most
    # likely to drive testcases on this target.
    if (target_root / "Cargo.toml").is_file():
        return "cargo"
    if (target_root / "go.mod").is_file():
        return "go"
    if (target_root / "Package.swift").is_file():
        return "swift"
    if (target_root / "pom.xml").is_file():
        return "maven"
    if (
        (target_root / "build.gradle").is_file()
        or (target_root / "build.gradle.kts").is_file()
        or (target_root / "settings.gradle").is_file()
        or (target_root / "settings.gradle.kts").is_file()
    ):
        return "gradle"
    if (
        any(target_root.glob("*.kts"))
        or any(target_root.glob("*.kt"))
        or any(target_root.glob("src/**/*.kt"))
        or any(target_root.glob("src/**/*.kts"))
    ):
        return "kotlin"
    if (
        (target_root / "pyproject.toml").is_file()
        or (target_root / "setup.py").is_file()
        or (target_root / "setup.cfg").is_file()
    ):
        return "python"
    if (target_root / "package.json").is_file():
        return "npm"
    if (target_root / "Gemfile").is_file() or any(target_root.glob("*.gemspec")):
        return "bundler"
    if (target_root / "composer.json").is_file():
        return "composer"
    if (target_root / "DESCRIPTION").is_file():
        return "rlang"
    if (target_root / "Makefile.PL").is_file() or any(target_root.glob("*.pm")):
        return "perl"
    return ""


# ─── Per-build-system runner defaults ───────────────────────────────
#
# When seed_toml writes a target.toml for a tree with no ASan binary
# detected, it also emits a starter [runner] block driven by the
# detected build system. The mapping below names the interpreter or
# driver plus its argument template; "{TESTCASE}" is substituted at
# run time. crash_patterns are language-specific runtime diagnostic
# strings (panics, tracebacks, race-detector reports) that lib/triage.sh
# treats as crash signals.
#
# This table is derived from the language registry in lib/languages.py.
# To add a new language or build_system, edit lib/languages.py — the
# registry is the single source of truth. Tests assert this dict and
# languages.runner_table() stay in sync so the silo cannot drift.
LANGUAGE_RUNNERS: dict[str, dict] = languages.runner_table()


def _java_home_candidates(home: str) -> list[Path]:
    base = Path(home)
    return [base / "bin" / "java", base / "Contents" / "Home" / "bin" / "java"]


def _java_home_for_bin(java_bin: Path) -> str:
    # .../Contents/Home/bin/java -> .../Contents/Home
    # .../bin/java               -> ...
    if java_bin.parent.name == "bin":
        return str(java_bin.parent.parent)
    return ""


def _java_is_usable(java_bin: Path) -> bool:
    if not java_bin.is_file() or not os.access(java_bin, os.X_OK):
        return False
    try:
        result = subprocess.run(
            [str(java_bin), "-version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0


def _detect_java_runner() -> tuple[str, list[str]]:
    """Return a usable Java executable and env entries, if one is discoverable."""
    for env_name in ("AUDIT_JAVA_HOME", "JAVA_HOME"):
        java_home = os.environ.get(env_name, "")
        if not java_home:
            continue
        for candidate in _java_home_candidates(java_home):
            if _java_is_usable(candidate):
                home = _java_home_for_bin(candidate)
                return str(candidate), ([f"JAVA_HOME={home}"] if home else [])

    path_java = shutil.which("java")
    if path_java:
        candidate = Path(path_java)
        if _java_is_usable(candidate):
            home = _java_home_for_bin(candidate)
            return str(candidate), ([f"JAVA_HOME={home}"] if home else [])

    return "", []


# ─── Build freshness (audit-owned lazy build) ───────────────────────
#
# bin/audit and bin/benchmark are the consumption points: they (re)build a
# stale or missing native sanitizer tree on demand so a checkout that moved
# since the last build is never audited against the wrong binary. These two
# helpers are the cheap probe and the stamp those callers and `setup-target
# --build` share. Native C/C++ only — language targets (cargo/go/pip) and
# browsers build elsewhere and report "skip".
_NATIVE_BUILD_SYSTEMS = {"cmake", "autotools", "meson"}
# VCS metadata and generated caches — never source whose change should force a
# rebuild. Pruned from the mtime walk so a fresh .audit log or __pycache__ entry
# can't masquerade as a source edit. (The sanitizer build trees themselves are
# pruned separately, by exact name — see san_build_dirs in build_freshness.)
_FRESHNESS_PRUNE_DIRS = {".git", ".hg", ".audit", "__pycache__", "node_modules"}


def _build_dir_for(target_root: Path, san: str) -> Path:
    suffix = os.environ.get("AUDIT_BUILD_SUFFIX", "")
    return Path(target_root) / f"build-{san}{suffix}"


def _source_state_signature(root: Path) -> str:
    """Hash the (relative path, mtime) of every source file under root.

    Compared across a build, a change in this signature flags ANY source-tree
    edit — modification or addition (an mtime/path appears), AND deletion or
    rename (a path disappears), which a bare max-mtime check misses because no
    remaining file is newer. Prunes VCS/cache dirs and only the canonical
    sanitizer build trees by exact name, so a sibling build compiled later (or
    this san's own tree) is excluded, while a source-support dir like build-aux/
    is still hashed. Errs toward "changed": any touch flips it (a harmless
    rebuild), but nothing real slips through as unchanged."""
    suffix = os.environ.get("AUDIT_BUILD_SUFFIX", "")
    san_build_dirs = {
        f"build-{s}{sfx}"
        for s in ("asan", "ubsan", "msan", "tsan")
        for sfx in ("", suffix)
    }
    entries: list[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in dirnames
            if d not in _FRESHNESS_PRUNE_DIRS and d not in san_build_dirs
        ]
        for fn in filenames:
            fp = Path(dirpath) / fn
            try:
                mt = fp.stat().st_mtime
            except OSError:
                continue  # races/broken symlinks: not a staleness signal
            entries.append(f"{os.path.relpath(fp, root)}\0{mt:.3f}")
    entries.sort()
    return hashlib.sha1(
        "\n".join(entries).encode("utf-8", "surrogatepass")
    ).hexdigest()


def build_write_stamp(target_root: "str | os.PathLike", san: str) -> bool:
    """Mark build-<san> as current with the source tree as of now.

    Writes build-<san>/.audit-build-stamp with the detected rev (line 1, for
    human diagnostics) and a source-state signature (line 2) that build_freshness
    recomputes and compares. Returns False (no-op) when the build dir does not
    exist."""
    root = Path(target_root)
    build_dir = _build_dir_for(root, san)
    if not build_dir.is_dir():
        return False
    rev = detect_rev(root) or ""
    sig = _source_state_signature(root)
    (build_dir / ".audit-build-stamp").write_text(
        f"{rev}\n{sig}\n", encoding="utf-8")
    return True


def build_freshness(target_root: "str | os.PathLike", san: str = "asan") -> str:
    """Classify build-<san> against the current source tree.

    Returns one of:
      * "skip"    — browser, or not a native C/C++ build system: no
                    build-<san> tree is expected, so freshness is N/A and
                    the caller must not try to (re)build one.
      * "missing" — native target with no build-<san> tree yet.
      * "stale"   — the source-state signature differs from the recorded
                    stamp (an upstream pull, branch switch, or local edit,
                    add, delete, or rename since the build), or the stamp
                    predates this mechanism.
      * "fresh"   — build-<san> exists and the source signature still matches.

    The signature (see _source_state_signature) catches every update mode
    uniformly — VCS or not, including deletion-only changes — and errs toward
    "stale" (a needless rebuild), never toward "fresh", which would audit the
    wrong binary."""
    root = Path(target_root)
    if root.name in _BROWSER_SLUGS:
        return "skip"
    if _detect_build_system(root) not in _NATIVE_BUILD_SYSTEMS:
        return "skip"
    build_dir = _build_dir_for(root, san)
    if not build_dir.is_dir():
        return "missing"
    stamp = build_dir / ".audit-build-stamp"
    if not stamp.exists():
        return "stale"  # built before stamping existed → rebuild to be safe
    try:
        stamp_lines = stamp.read_text(encoding="utf-8").splitlines()
    except OSError:
        return "stale"
    stored_sig = stamp_lines[1] if len(stamp_lines) >= 2 else ""
    if not stored_sig:
        return "stale"  # old-format (rev-only) stamp → rebuild to upgrade it
    return "fresh" if _source_state_signature(root) == stored_sig else "stale"


def language_runner_defaults(build_system: str) -> dict:
    """Return the default [runner] block for a build_system, or {}."""
    defaults = {k: (list(v) if isinstance(v, list) else v)
                for k, v in LANGUAGE_RUNNERS.get(build_system, {}).items()}
    if build_system in {"maven", "gradle", "kotlin"} and defaults:
        java_bin, java_env = _detect_java_runner()
        if java_bin:
            if build_system in {"maven", "gradle"}:
                defaults["bin"] = java_bin
            defaults["env"] = java_env
    return defaults


def _detect_upstream_url(target_root: Path) -> str:
    if (target_root / ".git").is_dir():
        try:
            out = subprocess.run(
                ["git", "-C", str(target_root), "config", "--get", "remote.origin.url"],
                capture_output=True, text=True, timeout=10,
            )
            if out.returncode == 0:
                return out.stdout.strip()
        except (OSError, subprocess.TimeoutExpired):
            pass
    if (target_root / ".hg").is_dir():
        try:
            out = subprocess.run(
                ["hg", "--cwd", str(target_root), "paths", "default"],
                capture_output=True, text=True, timeout=10,
            )
            if out.returncode == 0:
                return out.stdout.strip()
        except (OSError, subprocess.TimeoutExpired):
            pass
    return ""


def seed_toml(
    target_root: str | os.PathLike,
    out_path: str | os.PathLike,
    upstream_url: str = "",
    preserve_curated: bool = False,
) -> None:
    """Seed a starter target.toml — best-effort introspection.

    When ``preserve_curated`` is set and out_path already parses, the curated
    sections a fresh seed cannot re-derive — [threat_model].attacker_controls
    and the whole [s6_peers] block — are carried over from the existing file
    instead of reset to the conservative default (attacker_controls) or dropped
    (s6_peers, which a plain seed never emits). bin/setup-target uses this for a
    placeholder refresh, so filling one unrelated FILL_ME never discards an
    operator's hand- or LLM-curated threat model / peer set. A full re-seed
    (--force, missing, or unparseable file) leaves it False and regenerates."""
    root = Path(target_root)
    out = Path(out_path)
    slug = root.name
    is_browser = slug in _BROWSER_SLUGS

    # Read the curated sections to carry forward BEFORE the template is built,
    # so the render below can substitute them in place of the seed defaults.
    preserved_controls: Optional[list[str]] = None
    preserved_s6: Optional[tuple[str, list[str]]] = None
    if preserve_curated and out.exists():
        try:
            _existing = parse_toml(out)
        except Exception:
            _existing = {}
        _tm = _existing.get("threat_model")
        if isinstance(_tm, dict):
            _ac = _tm.get("attacker_controls")
            if isinstance(_ac, list):
                _ac = [str(x) for x in _ac if isinstance(x, str) and x]
                if _ac:
                    preserved_controls = _ac
        _s6 = _existing.get("s6_peers")
        if isinstance(_s6, dict):
            _peers = _s6.get("peers")
            if isinstance(_peers, list):
                _peers = [str(p) for p in _peers if isinstance(p, str) and p]
                if _peers:
                    _dom = _s6.get("domain")
                    preserved_s6 = (
                        str(_dom) if isinstance(_dom, str) else "",
                        _peers,
                    )
    # Detected up front: declared_cli_names() needs the build system to know
    # which manifest to read when biasing the asan_bin guess below.
    build_system = _detect_build_system(root)

    asan_bin = ""
    asan_lib = ""

    # AUDIT_BUILD_SUFFIX is set by bin/audit-container-shell so each
    # container image gets its own build tree; empty outside.
    suffix = os.environ.get("AUDIT_BUILD_SUFFIX", "")
    def _build_dir_name(san: str) -> str:
        return f"build-{san}{suffix}"

    asan_dir = root / _build_dir_name("asan")

    if is_browser:
        for cand in _BROWSER_BIN_CANDIDATES:
            full = asan_dir / cand
            if full.is_file() and os.access(full, os.X_OK):
                asan_bin = f"{_build_dir_name('asan')}/{cand}"
                break
    elif asan_dir.is_dir():
        # Candidate CLI names come from the target's own build manifests
        # (declared_cli_names), not a hardcoded per-project table. An
        # empty list just means we fall through to the free scan below.
        asan_bin = _detect_cli_bin(asan_dir, root, build_system, "asan")
        asan_lib = _detect_sanitizer_lib(asan_dir, root)

    if not upstream_url:
        upstream_url = _detect_upstream_url(root)
    pinned_rev = detect_rev(root)

    out.parent.mkdir(parents=True, exist_ok=True)

    upstream_v = upstream_url or "FILL_ME"
    build_system_v = build_system or "unknown"
    pinned_v = pinned_rev or "HEAD"

    # When introspection finds no ASan binary or archive, emit the field
    # commented out rather than as a "FILL_ME" placeholder string. A literal
    # placeholder is indistinguishable from a real path to downstream tools
    # (bin/export-repro would copy "build-asan/FILL_ME.a" into reproduce.sh
    # verbatim). The "FILL_ME" token stays in the comment so bin/setup-target's
    # grep-for-FILL_ME refresh trigger still fires, and so a human reviewer can
    # see at a glance that the field is unset. Header-only C++ libraries
    # legitimately have no asan_lib; the commented line is the steady state
    # for those targets.
    _asan_dir_name = _build_dir_name("asan")
    asan_bin_line = (
        f"asan_bin      = {toml_basic_string(asan_bin)}" if asan_bin
        else f'# asan_bin    = "{_asan_dir_name}/FILL_ME"      '
             '# uncomment + fill: ASan-instrumented CLI used by bin/run-asan'
    )
    asan_lib_line = (
        f"asan_lib      = {toml_basic_string(asan_lib)}" if asan_lib
        else f'# asan_lib    = "{_asan_dir_name}/FILL_ME.a"    '
             '# uncomment + fill if a // HARNESS testcase links a static archive'
    )

    lines = [
        "# target.toml — generated by bin/setup-target or bin/audit.",
        "# Review generated values; edit only unresolved or target-specific fields.",
        "# Paths are relative to target_root unless absolute.",
        "",
        f"target        = {toml_basic_string(slug)}",
        f"upstream_url  = {toml_basic_string(upstream_v)}",
        f"build_system  = {toml_basic_string(build_system_v)}",
        f"pinned_rev    = {toml_basic_string(pinned_v)}",
        "",
        "# Direct CLI binary — what `bin/run-asan generic` runs by default:",
        asan_bin_line,
        "",
        "# C-API harness build inputs (testcases with // HARNESS: link against this):",
        asan_lib_line,
        'includes      = [' + ", ".join(
            toml_basic_string(inc) for inc in _detect_include_dirs(root, _asan_dir_name)
        ) + "]",
        'link_libs     = ["-lm", "-lpthread"]',
        "",
        "# Optional: cmake target name used by maintainer reproduce.sh:",
        '# cmake_target  = "xmlcatalog"',
        "",
        "# Browser target? (1 enables browser/js mode, 0 = generic)",
        f'is_browser    = "{1 if is_browser else 0}"',
        "",
        "# ── Threat model (drives lib/triage.sh verdict matrix) ──────────",
        "# attacker_controls lists what an attacker can supply to the target.",
        "# A crash report's Trigger source: must be a subset of this set, or",
        "# triage demotes it from security to robustness. Tokens:",
        "#   bytes           input file/stream/packet bytes (most parsers)",
        "#   call-sequence   ordered API/script calls (browsers, JS engines,",
        "#                   plugin SDKs); call-order is accepted as a synonym",
        "#   timing          timing/scheduling control (browsers, JIT)",
        "#   race            concurrent threads/processes (servers, runtimes)",
        "#   protocol-state  multi-message protocol state (TLS, HTTP servers)",
        "#   env             environment / fs state (rare: shells, init code)",
        "#   fs-state        filesystem layout (rare: archive tools)",
        "#",
        "# Note: bytes control parsed input data, not arbitrary API parameters.",
        "# If a testcase reads a parsed field and passes it as an out-of-contract",
        "# offset/size/index/lifetime parameter, report Caller contract: violated",
        "# or Parameter control: harness-only rather than treating it as security.",
        "#",
        "# The value below is a conservative seed. For a stateful library this",
        "# byte-only default under-claims — run `bin/suggest-threat-model "
        + slug + "`",
        "# for an LLM-suggested model, or edit attacker_controls by hand.",
        "[threat_model]",
    ]
    attacker_controls = (
        preserved_controls if preserved_controls is not None
        else attacker_controls_for_seed(slug, is_browser)
    )
    # toml_basic_string escapes embedded quotes/backslashes. Default tokens are
    # clean, but a preserved value carried over from a hand-edited config may
    # contain a quote — a raw f'"{v}"' would emit invalid TOML and corrupt the
    # whole file on the next placeholder refresh.
    controls_rendered = ", ".join(toml_basic_string(v) for v in attacker_controls)
    lines.append(f"attacker_controls = [{controls_rendered}]")

    # Per-sanitizer harness-link library. ubsan/msan/tsan are detected the
    # same way as asan: scan build-<san>/ for a static archive, else the
    # canonical instrumented shared object. An operator who enables a
    # second sanitizer in `enabled` and builds build-<san>/ gets a working
    # <san>_lib without a hand-edit — and export-repro then links it just
    # like asan. When the build tree is absent (the steady state — only
    # asan is built by default) or the target is a browser (links no
    # library; harnesses drive the binary), detection returns "" and the
    # field stays a commented FILL_ME placeholder.
    def _san_lib_toml_line(san: str) -> str:
        field = f"{san}_lib"
        pad = " " * (len("ubsan_lib") - len(field))
        detected = "" if is_browser else _detect_sanitizer_lib(
            root / _build_dir_name(san), root)
        if detected:
            return f"{field}{pad} = {toml_basic_string(detected)}"
        return f'# {field}{pad} = "{_build_dir_name(san)}/FILL_ME.a"'

    ubsan_lib_line = _san_lib_toml_line("ubsan")
    msan_lib_line = _san_lib_toml_line("msan")
    tsan_lib_line = _san_lib_toml_line("tsan")

    # Detect whether this target should default to findings-only mode.
    # Heuristic: a non-native ecosystem (cargo/go/python/...) where we
    # did NOT find an ASan binary in build-asan/. Cargo + go targets
    # CAN run ASan (via -Zsanitizer=address / -msan), but the operator
    # opts in by editing target.toml afterwards. Native build systems
    # (cmake/meson/autotools/mach) default to ["asan"] as they did
    # before.
    _native_build_systems = {
        "cmake", "meson", "autotools", "mach", "",
        "unknown",
    }
    # Non-native ecosystems whose default [runner] already drives sanitizer
    # builds (e.g. `swift run -sanitize={SWIFT_SANITIZER}`), so they are
    # runnable sanitizer targets rather than findings-only ones.
    _sanitizer_runner_build_systems = {"swift"}
    _findings_only_default = (
        not is_browser
        and not asan_bin
        and build_system not in _native_build_systems
        and build_system not in _sanitizer_runner_build_systems
    )

    if _findings_only_default:
        lines += [
            "",
            "# ── Sanitizer policy ─────────────────────────────────────────",
            f"# {build_system!s} target with no ASan build detected — defaulting",
            "# to FINDINGS-ONLY mode. The audit harness runs testcases through",
            "# the [runner] block below and files diagnostics under findings/",
            "# rather than crashes/. To enable a sanitizer build, uncomment",
            "# an entry in `enabled` and point the corresponding *_bin at it.",
            "# See docs/guides/multi-language.md for the per-language picture.",
            "[sanitizer]",
            "enabled = []  # findings-only — uncomment a sanitizer to enable",
            '# enabled = ["asan"]',
            f'# asan_suppressions  = "{_build_dir_name("asan")}/asan-suppressions.txt"',
            f'# ubsan_suppressions = "{_build_dir_name("ubsan")}/ubsan-suppressions.txt"',
            f'# msan_suppressions  = "{_build_dir_name("msan")}/msan-suppressions.txt"',
            f'# tsan_suppressions  = "{_build_dir_name("tsan")}/tsan-suppressions.txt"',
            f'# ubsan_bin = "{_build_dir_name("ubsan")}/{slug}"',
            f'# msan_bin  = "{_build_dir_name("msan")}/{slug}"',
            f'# tsan_bin  = "{_build_dir_name("tsan")}/{slug}"',
            ubsan_lib_line,
            msan_lib_line,
            tsan_lib_line,
            '# race      — enable for Go targets; built via `go build -race`',
        ]
    else:
        lines += [
            "",
            "# ── Sanitizer policy ─────────────────────────────────────────",
            "# enabled: which sanitizers the audit harness should run for this",
            "# target. Only ASan is on by default. Tradeoffs:",
            "#   asan   memory corruption (OOB / UAF / double-free). High signal.",
            "#   msan   reads of uninitialized memory. Recommended for self-",
            "#          contained libraries; impractical for browsers because every",
            "#          dependency (including libc++) must be MSan-instrumented.",
            "#   ubsan  undefined behaviour. Noisier — enable with a curated",
            "#          -fsanitize= check list and expect to triage false",
            "#          positives like unsigned-integer-overflow or pointer-",
            "#          overflow patterns the project considers intentional.",
            "#   tsan   data races. Highest false-positive rate in practice;",
            "#          benign atomic_relaxed and intentional racy stats counters",
            "#          will fire. Only enable with a maintained suppressions",
            "#          file for the project's threading model.",
            "#   race   Go runtime race detector. Enable for Go targets built",
            "#          with `go build -race`; emits 'WARNING: DATA RACE'.",
            "# To turn off all sanitizers and audit in findings-only mode set",
            "# `enabled = []` and configure a [runner] block below.",
            "# Per-sanitizer suppression files are appended via *_OPTIONS=",
            "# suppressions=... at runner startup. Missing files emit a warning",
            "# but do not abort.",
            "[sanitizer]",
            'enabled = ["asan"]',
            f'# asan_suppressions  = "{_build_dir_name("asan")}/asan-suppressions.txt"',
            f'# ubsan_suppressions = "{_build_dir_name("ubsan")}/ubsan-suppressions.txt"',
            f'# msan_suppressions  = "{_build_dir_name("msan")}/msan-suppressions.txt"',
            f'# tsan_suppressions  = "{_build_dir_name("tsan")}/tsan-suppressions.txt"',
            f'# ubsan_bin = "{_build_dir_name("ubsan")}/' + (slug if not is_browser else "firefox") + '"',
            f'# msan_bin  = "{_build_dir_name("msan")}/' + (slug if not is_browser else "firefox") + '"',
            f'# tsan_bin  = "{_build_dir_name("tsan")}/' + (slug if not is_browser else "firefox") + '"',
            ubsan_lib_line,
            msan_lib_line,
            tsan_lib_line,
        ]

    # ── [runner] block (language-agnostic invocation) ───────────────
    # Always emit a [runner] block (commented unless we have a default
    # for the detected build_system). bin/probe and bin/run-asan generic
    # consult it when no sanitizer binary is configured. crash_patterns
    # is read by lib/triage.sh to detect runtime crashes (panics,
    # tracebacks, race-detector reports) on top of its built-in markers.
    runner_default = language_runner_defaults(build_system)

    _toml_string = toml_basic_string  # local alias for the existing call sites

    if runner_default:
        lines += [
            "",
            "# ── Runner (language / interpreter / driver invocation) ────────",
            f"# Auto-seeded for build_system = {build_system!r}. bin/probe routes",
            "# probes here when [sanitizer].enabled = [] or no <san>_bin is set.",
            "# The token '{TESTCASE}' is substituted with the testcase path at",
            "# run time. crash_patterns are regex strings layered on top of",
            "# lib/triage.sh's built-in language-agnostic crash markers.",
            "[runner]",
            f'bin            = {_toml_string(runner_default["bin"])}',
            "args           = ["
            + ", ".join(_toml_string(a) for a in runner_default["args"])
            + "]",
        ]
        if runner_default.get("env"):
            lines.append(
                "env            = ["
                + ", ".join(_toml_string(e) for e in runner_default["env"])
                + "]"
            )
        if runner_default.get("crash_patterns"):
            patterns_str = ",\n  ".join(
                _toml_string(p) for p in runner_default["crash_patterns"]
            )
            lines.append(f"crash_patterns = [\n  {patterns_str},\n]")
    else:
        lines += [
            "",
            "# ── Runner (language / interpreter / driver invocation) ────────",
            "# Uncomment and edit if this target is a script/interpreter audit.",
            "# bin/probe routes here when [sanitizer].enabled = [] or no",
            "# <san>_bin is set. '{TESTCASE}' expands to the testcase path.",
            "# [runner]",
            '# bin            = "/usr/bin/env"',
            '# args           = ["python3", "{TESTCASE}"]',
            '# env            = []',
            '# crash_patterns = []',
        ]

    # ── S4 differential pairs (per-engine CLI flag sets) ──────────
    # Only seeded for targets with a JS shell whose flag vocabulary is
    # known. Each shell has its own JIT-toggle flags; bin/run-asan js-diff
    # reads these and falls back to Firefox flags only when missing.
    # Validate by running `<shell> --help | grep <flag>`.
    pairs = _S4_DIFF_PAIRS_TAXONOMY.get(slug, {})
    if pairs:
        lines += [
            "",
            "# ── S4 differential pairs (JIT toggle flags) ───────────────",
            "# bin/run-asan js-diff runs the testcase under both flag sets and",
            "# diffs outputs. Each engine has its own flag vocabulary. Seeded",
            "# from the per-slug taxonomy in lib/target_config.py; edit if the",
            "# engine renames flags. Verify with `<js_shell> --help | grep <flag>`.",
            "[s4_diff_pairs]",
        ]
        for key in ("jit_off", "jit_eager"):
            args = pairs.get(key, [])
            if args:
                rendered = ", ".join(f'"{a}"' for a in args)
                lines.append(f"{key:<10} = [{rendered}]")

    # Carry a curated [s6_peers] forward. A plain seed never emits this section
    # (it is added by bin/suggest-peers / hand edits), so without this a
    # placeholder refresh would silently drop the operator's peer set.
    if preserved_s6 is not None:
        domain, peers = preserved_s6
        lines += [
            "",
            "# ── S6 peers (cross-project variant mining) — preserved from prior config ──",
            "[s6_peers]",
        ]
        if domain:
            lines.append(f"domain = {toml_basic_string(domain)}")
        lines.append(
            "peers = [" + ", ".join(toml_basic_string(p) for p in peers) + "]"
        )

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ─── High-level Python API for python callers ─────────────────────

@dataclass
class Config:
    """Parsed + normalized target config for Python consumers.

    Field names mirror the TARGET_* shell vars callers used to read.
    """
    slug: str = ""
    target_root: str = ""
    results_dir: str = ""
    target_rev: str = ""
    session_started: str = ""
    logdir: str = ""

    upstream_url: str = ""
    asan_bin: str = ""
    asan_lib: str = ""
    ubsan_bin: str = ""
    msan_bin: str = ""
    tsan_bin: str = ""
    ubsan_lib: str = ""
    msan_lib: str = ""
    tsan_lib: str = ""
    build_system: str = ""
    cmake_target: str = ""
    pinned_rev: str = ""
    is_browser: str = "0"

    includes: list[str] = field(default_factory=list)
    link_libs: list[str] = field(default_factory=list)
    attacker_controls: list[str] = field(default_factory=list)

    # Sanitizer policy: which sanitizers this target opts into, and where to
    # find optional per-sanitizer suppression files. Defaults to ASan only
    # UNLESS the target.toml explicitly sets `enabled = []` (findings-only
    # mode, suitable for interpreted-language targets where ASan cannot run).
    sanitizers_enabled: list[str] = field(default_factory=list)
    sanitizer_suppressions: dict = field(default_factory=dict)
    sanitizer_options: dict = field(default_factory=dict)
    # True when [sanitizer].enabled was present and explicitly empty (`= []`).
    # Used to skip the legacy ["asan"] default — an interpreted-language target
    # has no ASan build to detect, and forcing ASan would block bin/probe at
    # startup. Absent section keeps the existing default behavior.
    sanitizers_explicitly_disabled: bool = False

    # S4 (differential testing) per-engine CLI flag sets. Keys mirror the
    # [s4_diff_pairs] section in target.toml — currently jit_off and
    # jit_eager. Empty when the target has no [s4_diff_pairs] section.
    s4_diff_pairs: dict[str, list[str]] = field(default_factory=dict)

    # S6 (cross-project variant mining) peer projects. Populated only from
    # [s6_peers] in target.toml. Empty when no peers are configured.
    s6_peers: list[str] = field(default_factory=list)
    s6_domain: str = ""

    # [runner] table — language-agnostic program invocation. Used by
    # bin/probe / bin/run-asan generic when no ASan binary is configured
    # (or when sanitizers are explicitly disabled). The `bin` is an
    # interpreter or driver (python3, node, go, ruby, cargo, ...). The
    # `args` list takes literal arguments; the token "{TESTCASE}" is
    # substituted with the testcase path. The `env` list is a flat list
    # of "KEY=VAL" strings layered on the runtime environment.
    # `crash_patterns` is a list of regex strings that lib/triage.sh
    # treats as additional crash signals (Go data races, Python panics,
    # any project-specific runtime markers). Empty list means
    # triage uses only its built-in language-agnostic patterns.
    runner_bin: str = ""
    runner_args: list[str] = field(default_factory=list)
    runner_env: list[str] = field(default_factory=list)
    runner_crash_patterns: list[str] = field(default_factory=list)

    def attacker_controls_csv(self) -> str:
        if not self.attacker_controls:
            return "bytes"
        seen: set[str] = set()
        out: list[str] = []
        for v in self.attacker_controls:
            if v in seen:
                continue
            seen.add(v)
            out.append(v)
        return ",".join(out)

    def sanitizers_enabled_csv(self) -> str:
        if not self.sanitizers_enabled:
            # Explicitly disabled: return empty CSV. Callers distinguish
            # "no sanitizer" from "default asan" via the empty string.
            return "" if self.sanitizers_explicitly_disabled else "asan"
        seen: set[str] = set()
        out: list[str] = []
        for v in self.sanitizers_enabled:
            if v in seen:
                continue
            seen.add(v)
            out.append(v)
        return ",".join(out)

    def sanitizer_is_enabled(self, name: str) -> bool:
        return name.lower() in self.sanitizers_enabled

    def sanitizer_suppressions_path(self, name: str) -> str:
        """Absolute path to the suppression file for `name`, or "" if unset.

        Caller should check existence — missing files emit a warning at
        runner startup but do not abort, so audits can proceed before a
        per-target suppression list has been authored.
        """
        p = self.sanitizer_suppressions.get(name.lower(), "")
        if not p:
            return ""
        return self.resolve_path(p)

    def sanitizer_bin(self, name: str) -> str:
        name = name.lower()
        if name == "asan":
            return self.asan_bin
        if name == "ubsan":
            return self.ubsan_bin
        if name == "msan":
            return self.msan_bin
        if name == "tsan":
            return self.tsan_bin
        return ""

    def sanitizer_lib(self, name: str) -> str:
        name = name.lower()
        if name == "asan":
            return self.asan_lib
        if name == "ubsan":
            return self.ubsan_lib
        if name == "msan":
            return self.msan_lib
        if name == "tsan":
            return self.tsan_lib
        return ""

    def resolve_path(self, p: str) -> str:
        if not p:
            return ""
        if p.startswith("/"):
            return p
        norm = os.path.normpath(p)
        if norm == ".." or norm.startswith("../"):
            raise ValueError(f"target-relative path escapes TARGET_ROOT: {p}")
        suffix = os.environ.get("AUDIT_BUILD_SUFFIX", "")
        if suffix:
            head, sep, rest = norm.partition("/")
            if head in ("build-asan", "build-ubsan", "build-msan", "build-tsan"):
                norm = f"{head}{suffix}{sep}{rest}"
        return f"{self.target_root}/{norm}"


def _apply_attacker_controls(cfg: Config, raw: list, source_path: str) -> None:
    for item in raw:
        if not isinstance(item, str) or not item:
            continue
        norm = _normalize_attacker_control(item)
        if _is_valid_attacker_control(norm):
            cfg.attacker_controls.append(norm)
        else:
            valid = " ".join(ATTACKER_CONTROLS_VALID)
            sys.stderr.write(
                f"[target] ignored unknown attacker_controls token in {source_path}: "
                f"'{item}' (valid: {valid})\n"
            )
    if not cfg.attacker_controls:
        cfg.attacker_controls.append("bytes")


def _apply_sanitizer_section(cfg: Config, raw: dict, source_path: str) -> None:
    """Populate sanitizer policy from a [sanitizer] subtable.

    Accepts:
      enabled = ["asan", ...]              # list of sanitizer slugs
      <name>_suppressions = "path"          # path to suppression file
      <name>_options     = "key=val:..."   # extra runtime opts to append
      <name>_bin         = "path"           # per-sanitizer binary override
                                            # (asan_bin still lives top-level)
      <name>_lib         = "path"           # per-sanitizer C/C++ harness lib
                                            # (asan_lib still lives top-level)

    Unknown sanitizer slugs in `enabled` get a stderr warning and are
    dropped. If `enabled` is present and explicitly empty (`= []`), the
    loader honors it as findings-only mode — used by interpreted-language
    targets without a sanitizer build. Absent `enabled` keeps the legacy
    fallback to ["asan"].
    """
    # Distinguish "key absent" from "key present but empty". Real TOML
    # parsing returns the actual list; the lenient fallback parser also
    # accepts an empty `[]`. Using a sentinel default avoids confusing
    # them with each other.
    _SENTINEL: object = object()
    raw_enabled = raw.get("enabled", _SENTINEL)
    if raw_enabled is _SENTINEL:
        # Section present but `enabled` key absent → keep legacy default
        # (caller will append "asan" if cfg.sanitizers_enabled ends empty).
        pass
    elif isinstance(raw_enabled, list):
        if not raw_enabled:
            cfg.sanitizers_explicitly_disabled = True
        for item in raw_enabled:
            if not isinstance(item, str) or not item:
                continue
            norm = item.lower().strip()
            if norm in SANITIZERS_VALID:
                if norm not in cfg.sanitizers_enabled:
                    cfg.sanitizers_enabled.append(norm)
            else:
                valid = " ".join(SANITIZERS_VALID)
                sys.stderr.write(
                    f"[target] ignored unknown sanitizer in {source_path}: "
                    f"'{item}' (valid: {valid})\n"
                )
    for san in SANITIZERS_VALID:
        sup_key = f"{san}_suppressions"
        if isinstance(raw.get(sup_key), str) and raw[sup_key]:
            cfg.sanitizer_suppressions[san] = raw[sup_key]
        opt_key = f"{san}_options"
        if isinstance(raw.get(opt_key), str) and raw[opt_key]:
            cfg.sanitizer_options[san] = raw[opt_key]
        bin_key = f"{san}_bin"
        if isinstance(raw.get(bin_key), str) and raw[bin_key]:
            # asan_bin stays at top level for back-compat; only fill the
            # ubsan/msan/tsan/race overrides from this section. (Go's race
            # detector does not have a separate Config field — it is
            # detected from any binary's output by the runtime crash signal.)
            if san == "ubsan":
                cfg.ubsan_bin = raw[bin_key]
            elif san == "msan":
                cfg.msan_bin = raw[bin_key]
            elif san == "tsan":
                cfg.tsan_bin = raw[bin_key]
        lib_key = f"{san}_lib"
        if isinstance(raw.get(lib_key), str) and raw[lib_key]:
            # asan_lib stays at top level for back-compat; non-ASan
            # libraries live under [sanitizer] so one probe run cannot
            # accidentally link an ASan archive into an MSan/TSan/UBSan build.
            if san == "ubsan":
                cfg.ubsan_lib = raw[lib_key]
            elif san == "msan":
                cfg.msan_lib = raw[lib_key]
            elif san == "tsan":
                cfg.tsan_lib = raw[lib_key]


def _apply_runner_section(cfg: Config, raw: dict, source_path: str) -> None:
    """Populate cfg.runner_* from a [runner] subtable.

    Accepts:
      bin            = "/usr/bin/python3"       # interpreter or driver
      args           = ["-X", "dev", "{TESTCASE}"]  # literal args (use
                                                    # "{TESTCASE}" token
                                                    # for the testcase path)
      env            = ["GORACE=halt_on_error=1"]  # env vars layered on
      crash_patterns = ["my project's crash header"]  # extra regex signals

    Unknown keys are ignored. The loader keeps all the literal strings —
    bin/probe and lib/triage.sh substitute "{TESTCASE}" at run time.
    """
    if isinstance(raw.get("bin"), str) and raw["bin"]:
        cfg.runner_bin = raw["bin"]
    if isinstance(raw.get("args"), list):
        cfg.runner_args = [x for x in raw["args"] if isinstance(x, str)]
    if isinstance(raw.get("env"), list):
        cfg.runner_env = [x for x in raw["env"] if isinstance(x, str) and "=" in x]
    if isinstance(raw.get("crash_patterns"), list):
        cfg.runner_crash_patterns = [
            x for x in raw["crash_patterns"] if isinstance(x, str) and x
        ]


def load_toml_into(cfg: Config, toml_path: str | os.PathLike) -> None:
    """Parse a target.toml and populate the Config in-place.

    Mirrors target_load_toml: handles the [threat_model] section,
    normalizes call-order → call-sequence, drops unknown tokens with a
    stderr warning, defaults attacker_controls to ["bytes"] when empty.
    """
    parsed = parse_toml(toml_path)
    p = str(toml_path)
    cfg.attacker_controls = []
    cfg.includes = []
    cfg.link_libs = []
    cfg.sanitizers_enabled = []
    cfg.sanitizer_suppressions = {}
    cfg.sanitizer_options = {}
    cfg.sanitizers_explicitly_disabled = False
    cfg.s4_diff_pairs = {}
    cfg.s6_peers = []
    cfg.s6_domain = ""
    cfg.ubsan_bin = ""
    cfg.msan_bin = ""
    cfg.tsan_bin = ""
    cfg.ubsan_lib = ""
    cfg.msan_lib = ""
    cfg.tsan_lib = ""
    cfg.runner_bin = ""
    cfg.runner_args = []
    cfg.runner_env = []
    cfg.runner_crash_patterns = []
    for k, v in parsed.items():
        if k in ("target", "slug") and isinstance(v, str):
            cfg.slug = cfg.slug or v
        elif k == "upstream_url" and isinstance(v, str):
            cfg.upstream_url = v
        elif k == "asan_bin" and isinstance(v, str):
            cfg.asan_bin = v
        elif k == "asan_lib" and isinstance(v, str):
            cfg.asan_lib = v
        elif k == "cmake_target" and isinstance(v, str):
            cfg.cmake_target = v
        elif k == "build_system" and isinstance(v, str):
            cfg.build_system = v
        elif k == "pinned_rev" and isinstance(v, str):
            cfg.pinned_rev = v
        elif k == "is_browser":
            cfg.is_browser = _toml_value_to_str(v)
        elif k == "includes" and isinstance(v, list):
            cfg.includes = [x for x in v if isinstance(x, str) and x]
        elif k == "link_libs" and isinstance(v, list):
            cfg.link_libs = [x for x in v if isinstance(x, str) and x]
        elif k == "threat_model" and isinstance(v, dict):
            ac = v.get("attacker_controls", [])
            if isinstance(ac, list):
                _apply_attacker_controls(cfg, ac, p)
        elif k == "sanitizer" and isinstance(v, dict):
            _apply_sanitizer_section(cfg, v, p)
        elif k == "runner" and isinstance(v, dict):
            _apply_runner_section(cfg, v, p)
        elif k == "s4_diff_pairs" and isinstance(v, dict):
            for pair_key, pair_val in v.items():
                if isinstance(pair_val, list):
                    cfg.s4_diff_pairs[str(pair_key)] = [
                        x for x in pair_val if isinstance(x, str) and x
                    ]
        elif k == "s6_peers" and isinstance(v, dict):
            peers = v.get("peers", [])
            if isinstance(peers, list):
                cfg.s6_peers = [x for x in peers if isinstance(x, str) and x]
            dom = v.get("domain", "")
            if isinstance(dom, str):
                cfg.s6_domain = dom
    if not cfg.attacker_controls:
        cfg.attacker_controls.append("bytes")
    # Default: ASan only — UNLESS the target.toml explicitly set
    # `[sanitizer].enabled = []`, which means findings-only mode for
    # interpreted-language / sanitizer-less targets. The
    # sanitizers_explicitly_disabled flag preserves that distinction
    # across legacy callers that look at sanitizers_enabled directly.
    if not cfg.sanitizers_enabled and not cfg.sanitizers_explicitly_disabled:
        cfg.sanitizers_enabled.append("asan")

    # Normalize any path field that was stored as an audit-machine absolute
    # path (e.g. `auto-repair-target-toml` proposed
    # `/Users/.../targets/<slug>/build-asan/lib/libfoo.a`). Downstream
    # consumers (bin/export-repro _strip_sanitizer_build_prefix, the
    # seeder's `removeprefix`) assume target_root-relative form. Leaving
    # an absolute path in cfg causes reproduce.sh to emit
    # `$build/targets/<slug>/build-asan/...` instead of
    # `$build/build-asan/...`, breaking the maintainer build.
    _strip_target_root_paths(cfg)


def _strip_target_root_paths(cfg: Config) -> None:
    """Rewrite absolute target_root-prefixed values to target_root-relative."""
    root = (cfg.target_root or "").rstrip("/")
    if not root:
        return
    prefix = root + "/"

    def _rel(value: str) -> str:
        return value[len(prefix):] if value.startswith(prefix) else value

    cfg.asan_bin = _rel(cfg.asan_bin)
    cfg.asan_lib = _rel(cfg.asan_lib)
    cfg.ubsan_bin = _rel(cfg.ubsan_bin)
    cfg.ubsan_lib = _rel(cfg.ubsan_lib)
    cfg.msan_bin = _rel(cfg.msan_bin)
    cfg.msan_lib = _rel(cfg.msan_lib)
    cfg.tsan_bin = _rel(cfg.tsan_bin)
    cfg.tsan_lib = _rel(cfg.tsan_lib)
    # link_libs may carry bare archives or source compile inputs that
    # auto-repair-target-toml dragged in. Don't touch `-l…` / `-L…` /
    # `-Wl,…` flag entries.
    cfg.link_libs = [
        _rel(item) if not item.startswith("-") else item
        for item in cfg.link_libs
    ]


def load(start: str | os.PathLike) -> Config:
    """One-shot: discover slug dir, read .session-env, parse target.toml."""
    slug_dir = find_session_dir(start)
    if slug_dir is None:
        raise FileNotFoundError(
            f"no output/<slug>/.session-env found above: {start} "
            f"(run bin/audit first, or pass --target)"
        )
    cfg = Config()
    env = read_session_env(slug_dir)
    cfg.results_dir = env.get("RESULTS_DIR", "")
    cfg.target_root = env.get("TARGET_ROOT", "")
    cfg.slug = env.get("TARGET_SLUG", "")
    cfg.target_rev = env.get("TARGET_REV", "")
    cfg.session_started = env.get("SESSION_STARTED", "")
    cfg.logdir = env.get("LOGDIR", "")
    toml_path = target_toml_for_session_dir(slug_dir)
    if not toml_path.is_file():
        raise FileNotFoundError(f"target.toml not found: {toml_path}")
    load_toml_into(cfg, toml_path)
    return cfg


# ─── CLI subcommands (called by lib/target_config.sh shim) ──────────

def _cmd_parse_toml(args) -> int:
    try:
        parsed = parse_toml(args.file)
    except FileNotFoundError:
        sys.stderr.write(f"[target] target.toml not found: {args.file}\n")
        return 1
    except (tomllib.TOMLDecodeError if tomllib is not None else _FallbackTOMLDecodeError) as e:
        sys.stderr.write(f"[target] target.toml parse error in {args.file}: {e}\n")
        return 1
    sys.stdout.buffer.write(_emit_legacy_stream(parsed))
    return 0


def _cmd_seed_toml(args) -> int:
    seed_toml(args.target_root, args.out, args.upstream_url or "",
              preserve_curated=args.preserve_curated)
    return 0


def _cmd_detect_rev(args) -> int:
    print(detect_rev(args.target_root))
    return 0


def _cmd_detect_repo_type(args) -> int:
    print(detect_repo_type(args.target_root))
    return 0


def _cmd_find_session_dir(args) -> int:
    start = args.start or os.getcwd()
    d = find_session_dir(start)
    if d is None:
        return 1
    print(str(d))
    return 0


def _cmd_read_session_env(args) -> int:
    """Emit `export KEY="value"` lines for the bash shim to eval.

    Single-quote escape: replace ' with '\\'' which is the standard
    POSIX-shell literal-quote-with-embedded-quote idiom.
    """
    try:
        env = read_session_env(args.slug_dir)
    except FileNotFoundError as e:
        sys.stderr.write(f"[target] {e}\n")
        return 1
    for k, v in env.items():
        # shlex.quote produces the safest single-quoted form.
        sys.stdout.write(f"export {k}={shlex.quote(v)}\n")
    return 0


def _cmd_write_session_env(args) -> int:
    write_session_env(
        args.slug_dir, args.results, args.target_root,
        args.slug, args.rev, args.logdir,
    )
    return 0


def _cmd_refresh_build_fields(args) -> int:
    changed = refresh_detected_build_fields(Path(args.target_root), Path(args.out))
    print("changed" if changed else "unchanged")
    return 0


def _cmd_config_needs_reseed(args) -> int:
    # Exit 0 when an active placeholder needs a re-seed, 1 otherwise — shaped
    # for use as a shell `if` condition in bin/setup-target.
    return 0 if config_has_live_placeholder(Path(args.file)) else 1


def _cmd_build_freshness(args) -> int:
    # Print skip|missing|stale|fresh for the bash callers to branch on.
    print(build_freshness(args.target_root, args.sanitizer))
    return 0


def _cmd_build_write_stamp(args) -> int:
    build_write_stamp(args.target_root, args.sanitizer)
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="lib/target_config.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("parse-toml")
    sp.add_argument("file")
    sp.set_defaults(func=_cmd_parse_toml)

    sp = sub.add_parser("seed-toml")
    sp.add_argument("target_root")
    sp.add_argument("out")
    sp.add_argument("upstream_url", nargs="?", default="")
    sp.add_argument("--preserve-curated", action="store_true",
                    help="carry curated [threat_model]/[s6_peers] forward from "
                         "an existing out file (placeholder refresh)")
    sp.set_defaults(func=_cmd_seed_toml)

    sp = sub.add_parser("refresh-build-fields")
    sp.add_argument("target_root")
    sp.add_argument("out")
    sp.set_defaults(func=_cmd_refresh_build_fields)

    sp = sub.add_parser("config-needs-reseed")
    sp.add_argument("file")
    sp.set_defaults(func=_cmd_config_needs_reseed)

    sp = sub.add_parser("build-freshness")
    sp.add_argument("target_root")
    sp.add_argument("sanitizer", nargs="?", default="asan")
    sp.set_defaults(func=_cmd_build_freshness)

    sp = sub.add_parser("build-write-stamp")
    sp.add_argument("target_root")
    sp.add_argument("sanitizer", nargs="?", default="asan")
    sp.set_defaults(func=_cmd_build_write_stamp)

    sp = sub.add_parser("detect-rev")
    sp.add_argument("target_root")
    sp.set_defaults(func=_cmd_detect_rev)

    sp = sub.add_parser("detect-repo-type")
    sp.add_argument("target_root")
    sp.set_defaults(func=_cmd_detect_repo_type)

    sp = sub.add_parser("find-session-dir")
    sp.add_argument("start", nargs="?")
    sp.set_defaults(func=_cmd_find_session_dir)

    sp = sub.add_parser("read-session-env")
    sp.add_argument("slug_dir")
    sp.set_defaults(func=_cmd_read_session_env)

    sp = sub.add_parser("write-session-env")
    sp.add_argument("slug_dir")
    sp.add_argument("results")
    sp.add_argument("target_root")
    sp.add_argument("slug")
    sp.add_argument("rev")
    sp.add_argument("logdir")
    sp.set_defaults(func=_cmd_write_session_env)

    ns = ap.parse_args(argv)
    return ns.func(ns)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
